// ==================================================================
// comments.js — NaijaGenius Streak & End-of-Round Comment Banks
// ==================================================================

export function onThreeStreakLoss() {
  const comments = [
    "Wahala! 3 wrong answers straight? Your village people don show o! 😂",
    "Ehen! Na so una dey play? Abeg consult your ancestors before next round. 🤣",
    "3 errors in a row! You sure say you be Naija? 🤔😂",
    "Chai! 3 wrong answers, the spirit of 'try again' is strong with you. 💀",
    "Oga, 3 misses! Your brain don do 'reset'? No worry, we go laugh am later. 😁",
    "3 straight wahala! Naija no go hard for you? 😂",
    "Ah-ah! 3 wrongs in a row! You don make village people proud o. 👏🏾",
    "3 mistakes! Abeg go and drink garri, come back fresh. 😂",
    "E no easy for you o! 3 wrong answers, e be like say your brain dey on 'holiday'. 🧠✈️",
    "3 wrongs! You dey try to break record abi? Record of failure! 😂",
    "You no see am? 3 wrong answers! Even Fela go dey laugh. 😂",
    "3 misses! I dey suspect say you no be original Naija. 😏",
    "3 wrong! You don come with your 'I don't know' energy. 😂",
    "Ah! 3 wrong answers! E be like say you carry your 'tomorrow' go school. 😁",
    "3 times wrong! You just dey test my patience abi? 😂",
    "E don happen! 3 wrongs, your brain don 'hang'. Restart am! 🔄",
    "3 wrongs! You don enter 'village people' zone. 🏚️😂",
    "3 mistakes in a row! Your 'sabi' don run away! 🏃💨",
    "3 wrong answers! Na so you dey answer questions? 😂",
    "3 errors! You don show your 'village' side! 🌾😂",
    "3 wrongs! The way you dey answer, e be like say you dey 'search' for answer for Google. 🤣",
    "3 misses! You don show say you be 'Omo Oloju'! 😂",
    "3 wrong answers! Naija no go forgive you today! 🇳🇬😅",
    "3 wrongs! You don 'trip' for questions! 😂",
    "3 errors! Your 'power' don go down! ⚡😂",
    "3 wrongs! Abeg, go and 'refresh' your brain! 🔄",
    "3 mistakes! You don make me laugh! 😂",
    "3 wrong answers! You don 'carry' your 'bad luck' come! 🍀😂",
    "3 wrongs! Na 'wash' you dey wash today! 🧼😂",
    "3 errors! You don 'fall' for answer! 😂",
    "3 wrongs! E be like say you be 'amateur' for this game! 🥴😂",
    "3 misses! You don 'spoil' your record! 📉😂",
    "3 wrong answers! You dey 'try' to make me cry! 😢😂",
    "3 wrongs! Your 'brain' don 'jam'! 🧠💥",
    "3 errors! You don 'enter' my bad books! 📕😂",
    "3 wrongs! You go need 'prayer' for this one! 🙏😂",
    "3 mistakes! You don 'show' your 'weakness'! 💪😂",
    "3 wrong answers! Na so you dey 'represent' Naija? 🤦‍♂️😂",
    "3 wrongs! You don 'sabotage' yourself! 😂",
    "3 errors! E be like say you be 'wizard' for wrong answers! 🧙‍♂️😂",
    "3 wrongs! You don 'kill' my happiness! 💔😂",
    "3 mistakes! You go need 'counseling'! 🧑‍⚕️😂",
    "3 wrong answers! You don 'fail' again! 😂",
    "3 wrongs! I dey 'pity' you! 😢😂",
    "3 errors! You don 'burst' my brain! 🧠💥",
    "3 wrongs! You don 'prove' say you be 'human'! 🧑😂",
    "3 mistakes! You go need 'juju' to recover! 🔮😂",
    "3 wrong answers! You don 'carry' your 'trouble' come! 😂",
    "3 wrongs! Na 'try' you dey try, but e no work! 😂",
    "3 errors! You don 'make' me 'laugh'! 😂😂😂"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onFiveStreakLoss() {
  const comments = [
    "5 wrong answers! Your ancestors are crying! 😭😂",
    "Omo! 5 straight wrongs! You need deliverance! 🙏😂",
    "5 errors! You don 'collect' bad record! 📉😂",
    "5 wrongs! Your village people are celebrating! 🎉😂",
    "5 mistakes! You sure say you no be 'fool'? 😂",
    "5 wrongs! E be like say you dey 'answer' from another planet! 🌍😂",
    "5 wrongs! You don 'break' my heart! 💔😂",
    "5 errors! You need to 'reset' your brain! 🔄😂",
    "5 wrongs! Your 'sabi' don 'travel'! ✈️😂",
    "5 wrongs! You dey 'try' to make me 'cry'! 😢😂",
    "5 mistakes! You go need 'juju' to recover! 🔮😂",
    "5 wrongs! You don 'show' your 'village' side! 🌾😂",
    "5 errors! You don 'carry' your 'bad luck'! 🍀😂",
    "5 wrongs! Your brain don 'jam'! 🧠💥",
    "5 mistakes! You don 'enter' 'bad' territory! 😂",
    "5 wrongs! Na so you dey 'represent' Naija? 🇳🇬😅",
    "5 errors! You don 'fail' again! 😂",
    "5 wrongs! You go need 'prayer'! 🙏😂",
    "5 mistakes! You don 'kill' my happiness! 💔😂",
    "5 wrongs! You don 'prove' say you be 'human'! 🧑😂",
    "5 errors! You don 'burst' my brain! 🧠💥",
    "5 wrongs! You don 'carry' your 'trouble' come! 😂",
    "5 mistakes! You dey 'try' to make me 'laugh'! 😂😂",
    "5 wrongs! You don 'collect' your 'wahala'! 😂",
    "5 errors! You go need 'counseling'! 🧑‍⚕️😂",
    "5 wrongs! You don 'show' your 'weakness'! 💪😂",
    "5 mistakes! You don 'sabotage' yourself! 😂",
    "5 wrongs! You be 'wizard' for wrong answers! 🧙‍♂️😂",
    "5 errors! You don 'enter' my bad books! 📕😂",
    "5 wrongs! You don 'spoil' your record! 📉😂",
    "5 mistakes! You don 'carry' your 'bad luck' come! 🍀😂",
    "5 wrongs! E be like say you be 'amateur'! 🥴😂",
    "5 errors! You don 'fall' for answer! 😂",
    "5 wrongs! Na 'wash' you dey wash! 🧼😂",
    "5 mistakes! You don 'trip' for questions! 😂",
    "5 wrongs! You don 'show' your 'village' side! 🌾😂",
    "5 errors! You don 'make' me 'laugh'! 😂😂😂",
    "5 wrongs! You don 'carry' your 'trouble' come! 😂",
    "5 mistakes! You go need 'deliverance'! 🙏😂",
    "5 wrongs! You don 'collect' bad record! 📉😂",
    "5 errors! You don 'enter' 'bad' territory! 😂",
    "5 wrongs! Na so you dey 'answer' questions? 😂",
    "5 mistakes! You don 'prove' say you be 'human'! 🧑😂",
    "5 wrongs! You don 'kill' my happiness! 💔😂",
    "5 errors! You go need 'juju' to recover! 🔮😂",
    "5 wrongs! You don 'burst' my brain! 🧠💥",
    "5 mistakes! You dey 'try' to make me 'cry'! 😢😂",
    "5 wrongs! You don 'carry' your 'bad luck' come! 🍀😂",
    "5 errors! You don 'show' your 'weakness'! 💪😂",
    "5 wrongs! You don 'sabotage' yourself! 😂"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onCorrectAfterStreak() {
  const comments = [
    "Finally! You don correct your 'village' ways! 😂",
    "Ah! You don 'come back' from the dead! 🧟‍♂️😂",
    "Yes o! After all the wrongs, you 'remember' say you be Naija! 😎",
    "You don 'reset' your brain! 🔄😂",
    "E be like say you don 'pray' well! 🙏😂",
    "Correct! Your ancestors dey happy! 🎉😂",
    "You don 'prove' say you no be 'fool'! 😂",
    "Ah-ah! You don 'carry' your 'sabi' come back! 🧠💪",
    "You don 'wake' up! 🌅😂",
    "Correct! Your village people don 'rest'! 😂",
    "You don 'show' say you be original Naija! 🇳🇬😎",
    "E be like say you don 'jump' over 'wahala'! 😂",
    "You don 'collect' your 'power' back! ⚡😂",
    "Correct! Your brain don 'come' back! 🧠😂",
    "You don 'prove' say you be 'sharp guy'! 🔥",
    "You don 'break' the chain of wrongs! 🔗😂",
    "Correct! Your 'village people' don 'leave' you! 🏚️😂",
    "You don 'save' your reputation! 😂",
    "Ah! You don 'find' the correct answer! 🔍😂",
    "You don 'carry' your 'win' come! 🏆😂",
    "Correct! You don 'silence' your critics! 😂",
    "You don 'show' say you be 'ogbonge'! 💪",
    "E be like say you don 'pray' to your ancestors! 🙏😂",
    "You don 'collect' your 'praise'! 👏😂",
    "Correct! Your 'sabi' don return! 🧠😂",
    "You don 'overcome' the 'bad luck'! 🍀😂",
    "Ah! You don 'carry' your 'win'! 🎉😂",
    "You don 'prove' say you be 'Naija champion'! 🇳🇬🏆",
    "Correct! Your brain don 'wake' up! 🌅😂",
    "You don 'stop' the 'wahala'! 😂",
    "You don 'find' your 'way'! 🧭😂",
    "Correct! Your 'village people' don 'rest'! 😂",
    "You don 'collect' your 'power' back! ⚡😂",
    "You don 'show' say you be 'sharp guy'! 🔥",
    "You don 'break' the chain of wrongs! 🔗😂",
    "Correct! Your 'sabi' don return! 🧠😂",
    "You don 'carry' your 'win' come! 🏆😂",
    "You don 'prove' say you be 'Naija champion'! 🇳🇬🏆",
    "Correct! Your brain don 'wake' up! 🌅😂",
    "You don 'stop' the 'wahala'! 😂",
    "You don 'find' your 'way'! 🧭😂",
    "Correct! Your 'village people' don 'rest'! 😂",
    "You don 'collect' your 'power' back! ⚡😂",
    "You don 'show' say you be 'sharp guy'! 🔥",
    "You don 'break' the chain of wrongs! 🔗😂",
    "Correct! Your 'sabi' don return! 🧠😂",
    "You don 'carry' your 'win' come! 🏆😂",
    "You don 'prove' say you be 'Naija champion'! 🇳🇬🏆",
    "Correct! Your brain don 'wake' up! 🌅😂",
    "You don 'stop' the 'wahala'! 😂"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onTwoStreakWin() {
  const comments = [
    "Ah! 2 correct! You be 'sharp guy' o! 🔥",
    "2 straight correct! Your brain dey 'work'! 🧠💪",
    "Yes o! 2 correct! You dey 'represent'! 🇳🇬😎",
    "2 correct! E be like say you 'know' the answer! 😂",
    "You don 'collect' 2 correct! Continue like this! 🔥",
    "2 correct! Your 'sabi' dey 'shine'! ✨",
    "You be 'original Naija'! 2 correct! 🏆",
    "2 correct! You dey 'make' me proud! 👏",
    "Ah! 2 correct! You don 'wake' up! 🌅😂",
    "You dey 'follow' the right 'way'! 2 correct! 🧭",
    "2 correct! Your 'village people' don 'rest'! 😂",
    "You don 'collect' 2 correct! Continue! 🔥",
    "2 correct! You be 'ogbonge'! 💪",
    "Your brain dey 'work' today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey 'fire'! 🔥",
    "2 correct! Your 'sabi' dey 'show'! ✨",
    "You dey 'carry' your 'win'! 2 correct! 🏆",
    "Ah! 2 correct! You don 'break' the chain! 🔗😂",
    "2 correct! You dey 'make' me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be 'champion'! 🏆",
    "2 correct! Your brain dey 'sharp'! 🔪🧠",
    "You don 'collect' 2 correct! Continue like this! 🔥",
    "2 correct! You dey 'represent' Naija well! 🇳🇬😎",
    "Your 'sabi' dey 'shine'! 2 correct! ✨",
    "2 correct! You don 'prove' say you be 'sharp guy'! 🔥",
    "Ah! 2 correct! You dey 'carry' the day! ☀️😂",
    "2 correct! Your brain dey 'work'! 🧠💪",
    "You don 'collect' 2 correct! Continue! 🔥",
    "2 correct! You be 'ogbonge'! 💪",
    "Your brain dey 'work' today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey 'fire'! 🔥",
    "2 correct! Your 'sabi' dey 'show'! ✨",
    "You dey 'carry' your 'win'! 2 correct! 🏆",
    "Ah! 2 correct! You don 'break' the chain! 🔗😂",
    "2 correct! You dey 'make' me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be 'champion'! 🏆",
    "2 correct! Your brain dey 'sharp'! 🔪🧠",
    "You don 'collect' 2 correct! Continue like this! 🔥",
    "2 correct! You dey 'represent' Naija well! 🇳🇬😎",
    "Your 'sabi' dey 'shine'! 2 correct! ✨",
    "2 correct! You don 'prove' say you be 'sharp guy'! 🔥",
    "Ah! 2 correct! You dey 'carry' the day! ☀️😂",
    "2 correct! Your brain dey 'work'! 🧠💪",
    "You don 'collect' 2 correct! Continue! 🔥",
    "2 correct! You be 'ogbonge'! 💪",
    "Your brain dey 'work' today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey 'fire'! 🔥",
    "2 correct! Your 'sabi' dey 'show'! ✨",
    "You dey 'carry' your 'win'! 2 correct! 🏆",
    "Ah! 2 correct! You don 'break' the chain! 🔗😂"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onFiveStreakWin() {
  const comments = [
    "5 correct! You be 'Odogwu'! 🔥🔥🔥",
    "5 straight! Your brain dey 'overheat'! 🧠🔥",
    "Ah! 5 correct! You dey 'chop' the game! 🍽️😂",
    "5 correct! You be 'legend' for this round! 🏆",
    "Your 'sabi' dey 'too much'! 5 correct! 🔥",
    "5 correct! Your ancestors dey 'proud'! 🎉😂",
    "You don 'collect' 5 correct! You dey 'break' record! 📉🔥",
    "5 correct! You be 'Naija genius'! 🇳🇬🧠",
    "Ah! 5 correct! You dey 'carry' the game! 💪",
    "5 correct! Your brain dey 'sharper' than knife! 🔪🧠",
    "You don 'prove' say you be 'ogbonge'! 5 correct! 🔥",
    "5 correct! You dey 'make' me 'speechless'! 😮😂",
    "Your 'sabi' dey 'shine' too much! 5 correct! ✨",
    "5 correct! You be 'champion' for this category! 🏆",
    "Ah! 5 correct! You don 'silence' your 'village people'! 😂",
    "5 correct! You dey 'fire' on all cylinders! 🔥",
    "You don 'collect' 5 correct! You be 'Wizard'! 🧙‍♂️😂",
    "5 correct! Your brain dey 'work' overtime! 🧠💪",
    "Yes o! 5 correct! You dey 'represent' Naija well! 🇳🇬😎",
    "5 correct! You be 'Omo Naija' wey sabi! 💪",
    "Your 'sabi' dey 'too much'! 5 correct! 🔥",
    "5 correct! Your ancestors dey 'proud'! 🎉😂",
    "You don 'collect' 5 correct! You dey 'break' record! 📉🔥",
    "5 correct! You be 'Naija genius'! 🇳🇬🧠",
    "Ah! 5 correct! You dey 'carry' the game! 💪",
    "5 correct! Your brain dey 'sharper' than knife! 🔪🧠",
    "You don 'prove' say you be 'ogbonge'! 5 correct! 🔥",
    "5 correct! You dey 'make' me 'speechless'! 😮😂",
    "Your 'sabi' dey 'shine' too much! 5 correct! ✨",
    "5 correct! You be 'champion' for this category! 🏆",
    "Ah! 5 correct! You don 'silence' your 'village people'! 😂",
    "5 correct! You dey 'fire' on all cylinders! 🔥",
    "You don 'collect' 5 correct! You be 'Wizard'! 🧙‍♂️😂",
    "5 correct! Your brain dey 'work' overtime! 🧠💪",
    "Yes o! 5 correct! You dey 'represent' Naija well! 🇳🇬😎",
    "5 correct! You be 'Omo Naija' wey sabi! 💪",
    "Your 'sabi' dey 'too much'! 5 correct! 🔥",
    "5 correct! Your ancestors dey 'proud'! 🎉😂",
    "You don 'collect' 5 correct! You dey 'break' record! 📉🔥",
    "5 correct! You be 'Naija genius'! 🇳🇬🧠",
    "Ah! 5 correct! You dey 'carry' the game! 💪",
    "5 correct! Your brain dey 'sharper' than knife! 🔪🧠",
    "You don 'prove' say you be 'ogbonge'! 5 correct! 🔥",
    "5 correct! You dey 'make' me 'speechless'! 😮😂",
    "Your 'sabi' dey 'shine' too much! 5 correct! ✨",
    "5 correct! You be 'champion' for this category! 🏆",
    "Ah! 5 correct! You don 'silence' your 'village people'! 😂",
    "5 correct! You dey 'fire' on all cylinders! 🔥",
    "You don 'collect' 5 correct! You be 'Wizard'! 🧙‍♂️😂",
    "5 correct! Your brain dey 'work' overtime! 🧠💪"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function getEndOfRoundComment(score) {
  // Score bands
  let band = [];
  if (score >= 0 && score <= 20) {
    band = [
      "0–20? Ah! Your village people don come for you o! 😂",
      "20 points? You dey try, but e no reach! 😂",
      "Score 0–20! Your ancestors are laughing! 😂",
      "20 points? You fit do better, but today no be your day! 😂",
      "0–20! You don 'collect' 'village' score! 😂",
      "20 points? You dey 'try' but e no work! 😂",
      "Score 0–20! Your brain don 'shut down'! 🧠💤",
      "20 points? You fit 'pass' but you no 'pass'! 😂",
      "0–20! You don 'carry' your 'bad luck' come! 🍀😂",
      "20 points? You be 'amateur' for this game! 😂",
      "Score 0–20! Your 'sabi' don 'run' away! 🏃💨",
      "20 points? You dey 'try' but e no 'sweet'! 😂",
      "0–20! Your village people are 'celebrating'! 🎉😂",
      "20 points? You go need 'prayer' for next round! 🙏😂",
      "Score 0–20! You don 'spoil' your record! 📉😂",
      "20 points? You be 'Omo Oloju' for today! 😂",
      "0–20! Your brain don 'jam'! 🧠💥",
      "20 points? You dey 'make' me laugh! 😂",
      "Score 0–20! You don 'carry' your 'trouble' come! 😂",
      "20 points? You fit 'pass' but you no 'pass'! 😂"
    ];
  } else if (score >= 21 && score <= 30) {
    band = [
      "21–30! You try small, but you still dey 'carry' wahala! 😂",
      "30 points? You dey 'wake' up slowly! 🌅😂",
      "Score 21–30! You 'sabi' small, but no be 'complete'! 😂",
      "30 points? You dey 'try' but e no 'reach'! 😂",
      "21–30! Your ancestors dey 'watch' you! 👀😂",
      "30 points? You fit 'do better' but e no 'bad'! 😂",
      "Score 21–30! You dey 'carry' your 'sabi' come! 🧠😂",
      "30 points? You dey 'try' but you no 'reach' top! 😂",
      "21–30! You don 'collect' 'middle' score! 😂",
      "30 points? You be 'student' wey dey 'try'! 📚😂",
      "Score 21–30! You 'sabi' small, but you go 'learn'! 😂",
      "30 points? You dey 'make' me 'proud' small! 👏😂",
      "21–30! Your brain dey 'wake' up! 🌅😂",
      "30 points? You fit 'pass' next time! 💪😂",
      "Score 21–30! You dey 'carry' your 'win' come! 🏆😂",
      "30 points? You dey 'try' but e no 'sweet'! 😂",
      "21–30! Your ancestors dey 'smile'! 😊😂",
      "30 points? You be 'Omo Naija' wey dey 'try'! 😂",
      "Score 21–30! You don 'collect' your 'points'! 😂",
      "30 points? You dey 'make' me 'laugh'! 😂"
    ];
  } else if (score >= 31 && score <= 50) {
    band = [
      "31–50! You dey 'carry' your 'sabi' come! 🧠💪",
      "50 points? You dey 'try' but e no 'reach' 100! 😂",
      "Score 31–50! You be 'average' Naija! 🇳🇬😎",
      "50 points? You dey 'wake' up well! 🌅😂",
      "31–50! Your ancestors dey 'proud' small! 🎉😂",
      "50 points? You dey 'carry' your 'win'! 🏆😂",
      "Score 31–50! You 'sabi' but no be 'ogbonge'! 😂",
      "50 points? You fit 'do better' but e no 'bad'! 😂",
      "31–50! You don 'collect' 'middle' score! 😂",
      "50 points? You be 'student' wey dey 'try'! 📚😂",
      "Score 31–50! You dey 'make' me 'proud'! 👏😂",
      "50 points? You dey 'carry' your 'sabi' come! 🧠😂",
      "31–50! Your brain dey 'work'! 🧠💪",
      "50 points? You fit 'pass' next time! 💪😂",
      "Score 31–50! You be 'Naija champion' small! 🇳🇬🏆",
      "50 points? You dey 'try' but e no 'reach' top! 😂",
      "31–50! Your ancestors dey 'smile'! 😊😂",
      "50 points? You be 'Omo Naija' wey dey 'try'! 😂",
      "Score 31–50! You don 'collect' your 'points'! 😂",
      "50 points? You dey 'make' me 'laugh'! 😂"
    ];
  } else if (score >= 51 && score <= 80) {
    band = [
      "51–80! You be 'sharp guy'! 🔥",
      "80 points? You dey 'carry' your 'sabi' well! 🧠💪",
      "Score 51–80! Your ancestors dey 'proud'! 🎉😂",
      "80 points? You be 'Naija genius' small! 🇳🇬🧠",
      "51–80! You dey 'wake' up! 🌅😂",
      "80 points? You dey 'carry' your 'win'! 🏆😂",
      "Score 51–80! You 'sabi' well well! 😎",
      "80 points? You fit 'reach' 100 next time! 💪😂",
      "51–80! You don 'collect' 'good' score! 😂",
      "80 points? You be 'student' wey dey 'shine'! 📚🔥",
      "Score 51–80! You dey 'make' me 'proud'! 👏😂",
      "80 points? You dey 'carry' your 'sabi' come! 🧠😂",
      "51–80! Your brain dey 'work' well! 🧠💪",
      "80 points? You fit 'pass' next time! 💪😂",
      "Score 51–80! You be 'Naija champion'! 🇳🇬🏆",
      "80 points? You dey 'try' but e no 'reach' top! 😂",
      "51–80! Your ancestors dey 'smile'! 😊😂",
      "80 points? You be 'Omo Naija' wey dey 'try'! 😂",
      "Score 51–80! You don 'collect' your 'points'! 😂",
      "80 points? You dey 'make' me 'laugh'! 😂"
    ];
  } else if (score >= 81 && score <= 100) {
    band = [
      "81–100! You be 'ogbonge'! 🔥🔥",
      "100 points? You dey 'carry' your 'sabi' well! 🧠💪",
      "Score 81–100! Your ancestors dey 'dance'! 💃🕺",
      "100 points? You be 'Naija genius'! 🇳🇬🧠",
      "81–100! You dey 'wake' up! 🌅😂",
      "100 points? You dey 'carry' your 'win'! 🏆😂",
      "Score 81–100! You 'sabi' well well! 😎",
      "100 points? You fit 'reach' 120 next time! 💪😂",
      "81–100! You don 'collect' 'excellent' score! 😂",
      "100 points? You be 'student' wey dey 'shine'! 📚🔥",
      "Score 81–100! You dey 'make' me 'proud'! 👏😂",
      "100 points? You dey 'carry' your 'sabi' come! 🧠😂",
      "81–100! Your brain dey 'work' well! 🧠💪",
      "100 points? You fit 'pass' next time! 💪😂",
      "Score 81–100! You be 'Naija champion'! 🇳🇬🏆",
      "100 points? You dey 'try' but e no 'reach' top! 😂",
      "81–100! Your ancestors dey 'smile'! 😊😂",
      "100 points? You be 'Omo Naija' wey dey 'try'! 😂",
      "Score 81–100! You don 'collect' your 'points'! 😂",
      "100 points? You dey 'make' me 'laugh'! 😂"
    ];
  } else if (score >= 101 && score <= 110) {
    band = [
      "101–110! You be 'Odogwu'! 🔥🔥🔥",
      "110 points? You dey 'carry' your 'sabi' well! 🧠💪",
      "Score 101–110! Your ancestors dey 'dance'! 💃🕺",
      "110 points? You be 'Naija genius'! 🇳🇬🧠",
      "101–110! You dey 'wake' up! 🌅😂",
      "110 points? You dey 'carry' your 'win'! 🏆😂",
      "Score 101–110! You 'sabi' well well! 😎",
      "110 points? You dey 'carry' your 'sabi' come! 🧠😂",
      "101–110! Your brain dey 'work' well! 🧠💪",
      "110 points? You fit 'reach' 120 next time! 💪😂",
      "Score 101–110! You dey 'make' me 'proud'! 👏😂",
      "110 points? You dey 'carry' your 'sabi' come! 🧠😂",
      "101–110! You be 'Naija champion'! 🇳🇬🏆",
      "110 points? You dey 'try' but e no 'reach' top! 😂",
      "101–110! Your ancestors dey 'smile'! 😊😂",
      "110 points? You be 'Omo Naija' wey dey 'try'! 😂",
      "Score 101–110! You don 'collect' your 'points'! 😂",
      "110 points? You dey 'make' me 'laugh'! 😂",
      "101–110! You be 'legend' for this round! 🏆",
      "110 points? You dey 'carry' your 'sabi' well! 🧠💪"
    ];
  } else if (score >= 111 && score <= 120) {
    band = [
      "111–120! You be 'Odogwu' wey no dey 'choke'! 🔥🔥🔥",
      "120 points? You dey 'carry' your 'sabi' well! 🧠💪",
      "Score 111–120! Your ancestors dey 'dance'! 💃🕺",
      "120 points? You be 'Naija genius'! 🇳🇬🧠",
      "111–120! You dey 'wake' up! 🌅😂",
      "120 points? You dey 'carry' your 'win'! 🏆😂",
      "Score 111–120! You 'sabi' well well! 😎",
      "120 points? You dey 'carry' your 'sabi' come! 🧠😂",
      "111–120! Your brain dey 'work' well! 🧠💪",
      "120 points? You dey 'carry' your 'sabi' well! 🧠💪",
      "Score 111–120! You dey 'make' me 'proud'! 👏😂",
      "120 points? You be 'legend' for this round! 🏆",
      "111–120! Your ancestors dey 'smile'! 😊😂",
      "120 points? You be 'Omo Naija' wey dey 'try'! 😂",
      "Score 111–120! You don 'collect' your 'points'! 😂",
      "120 points? You dey 'make' me 'laugh'! 😂",
      "111–120! You be 'Odogwu' wey no dey 'choke'! 🔥🔥🔥",
      "120 points? You dey 'carry' your 'sabi' well! 🧠💪",
      "Score 111–120! Your ancestors dey 'dance'! 💃🕺",
      "120 points? You be 'Naija genius'! 🇳🇬🧠"
    ];
  }
  return band[Math.floor(Math.random() * band.length)];
}