// ==================================================================
// comments.js — NaijaGenius Streak & End-of-Round Comment Banks
// ==================================================================

export function onThreeStreakLoss() {
  const comments = [
    // ===== ORIGINAL 50 =====
    "Wahala! 3 wrong answers straight? Your village people don show o! 😂",
    "Ehen! Na so una dey play? Abeg consult your ancestors before next round. 🤣",
    "3 errors in a row! You sure say you be Naija? 🤔😂",
    "Chai! 3 wrong answers, the spirit of try again is strong with you. 💀",
    "Oga, 3 misses! Your brain don do reset? No worry, we go laugh am later. 😁",
    "3 straight wahala! Naija no go hard for you? 😂",
    "Ah-ah! 3 wrongs in a row! You don make village people proud o. 👏🏾",
    "3 mistakes! Abeg go and drink garri, come back fresh. 😂",
    "E no easy for you o! 3 wrong answers, e be like say your brain dey on holiday. 🧠✈️",
    "3 wrongs! You dey try to break record abi? Record of failure! 😂",
    "You no see am? 3 wrong answers! Even Fela go dey laugh. 😂",
    "3 misses! I dey suspect say you no be original Naija. 😏",
    "3 wrong! You don come with your I don't know energy. 😂",
    "Ah! 3 wrong answers! E be like say you carry your tomorrow go school. 😁",
    "3 times wrong! You just dey test my patience abi? 😂",
    "E don happen! 3 wrongs, your brain don hang. Restart am! 🔄",
    "3 wrongs! You don enter village people zone. 🏚️😂",
    "3 mistakes in a row! Your sabi don run away! 🏃💨",
    "3 wrong answers! Na so you dey answer questions? 😂",
    "3 errors! You don show your village side! 🌾😂",
    "3 wrongs! The way you dey answer, e be like say you dey search for answer for Google. 🤣",
    "3 misses! You don show say you be Omo Oloju! 😂",
    "3 wrong answers! Naija no go forgive you today! 🇳🇬😅",
    "3 wrongs! You don trip for questions! 😂",
    "3 errors! Your power don go down! ⚡😂",
    "3 wrongs! Abeg, go and refresh your brain! 🔄",
    "3 mistakes! You don make me laugh! 😂",
    "3 wrong answers! You don carry your bad luck come! 🍀😂",
    "3 wrongs! Na wash you dey wash today! 🧼😂",
    "3 errors! You don fall for answer! 😂",
    "3 wrongs! E be like say you be amateur for this game! 🥴😂",
    "3 misses! You don spoil your record! 📉😂",
    "3 wrong answers! You dey try to make me cry! 😢😂",
    "3 wrongs! Your brain don jam! 🧠💥",
    "3 errors! You don enter my bad books! 📕😂",
    "3 wrongs! You go need prayer for this one! 🙏😂",
    "3 mistakes! You don show your weakness! 💪😂",
    "3 wrong answers! Na so you dey represent Naija? 🤦‍♂️😂",
    "3 wrongs! You don sabotage yourself! 😂",
    "3 errors! E be like say you be wizard for wrong answers! 🧙‍♂️😂",
    "3 wrongs! You don kill my happiness! 💔😂",
    "3 mistakes! You go need counseling! 🧑‍⚕️😂",
    "3 wrong answers! You don fail again! 😂",
    "3 wrongs! I dey pity you! 😢😂",
    "3 errors! You don burst my brain! 🧠💥",
    "3 wrongs! You don prove say you be human! 🧑😂",
    "3 mistakes! You go need juju to recover! 🔮😂",
    "3 wrong answers! You don carry your trouble come! 😂",
    "3 wrongs! Na try you dey try, but e no work! 😂",
    "3 errors! You don make me laugh! 😂😂😂",

    // ===== 100 NEW COMMENTS =====
    "3 wrongs! Your village people don gather for meeting o! 🏘️😂",
    "3 errors! E be like say you carry your brain go fault! 🧠⚡",
    "3 wrong answers! Your ancestors are shaking their heads! 😂",
    "3 misses! You sure say you no be Baba Ijebu for this game? 😂",
    "3 wrongs! Naija don enter your eye! 😂",
    "3 mistakes! You dey chop wrong answers like garri! 🍲😂",
    "3 wrongs! You don enter error zone! 🚧😂",
    "3 errors! Your brain don logout! 🔄😂",
    "3 wrong answers! You dey try but e no click! 😂",
    "3 misses! You go need juju to fix this one! 🔮😂",
    "3 wrongs! Your village people dey dance for your failure! 💃😂",
    "3 mistakes! You don collect three wrongs! 😂",
    "3 wrong answers! You dey test my patience! 😂",
    "3 errors! Your brain don jam with wrong answers! 🧠💥",
    "3 wrongs! You don enter bad record! 📉😂",
    "3 misses! You dey carry your bad luck o! 🍀😂",
    "3 wrong answers! You be professor of wrong answers! 🎓😂",
    "3 errors! You don spoil your reputation! 😂",
    "3 wrongs! You go need prayer to recover! 🙏😂",
    "3 mistakes! Your sabi don run far! 🏃💨",
    "3 wrong answers! You dey try to make me sad! 😢😂",
    "3 errors! You don enter my bad books! 📕😂",
    "3 wrongs! You be Omo Oloju for this game! 😂",
    "3 misses! You don carry your trouble come! 😂",
    "3 wrong answers! You dey try to break record! 😂",
    "3 errors! You don show your village side! 🌾😂",
    "3 wrongs! You go need deliverance! 🙏😂",
    "3 mistakes! You don collect bad omen! 😂",
    "3 wrong answers! You dey try to make me cry! 😢😂",
    "3 errors! You don kill my happiness! 💔😂",
    "3 wrongs! You be wizard for wrong answers! 🧙‍♂️😂",
    "3 misses! You go need counseling! 🧑‍⚕️😂",
    "3 wrong answers! You don fail again! 😂",
    "3 errors! You don burst my brain! 🧠💥",
    "3 wrongs! You don prove say you be human! 🧑😂",
    "3 mistakes! You don sabotage yourself! 😂",
    "3 wrong answers! You dey try to make me laugh! 😂😂",
    "3 errors! You don carry your bad luck! 🍀😂",
    "3 wrongs! You go need juju to recover! 🔮😂",
    "3 misses! You don enter my bad books! 📕😂",
    "3 wrong answers! You don spoil your record! 📉😂",
    "3 errors! You be amateur for this game! 🥴😂",
    "3 wrongs! You don fall for answer! 😂",
    "3 mistakes! Na wash you dey wash! 🧼😂",
    "3 wrong answers! You don trip for questions! 😂",
    "3 errors! You don show your village side! 🌾😂",
    "3 wrongs! You don make me laugh! 😂😂😂",
    "3 misses! You don carry your trouble come! 😂",
    "3 wrong answers! You go need deliverance! 🙏😂",
    "3 errors! You don collect bad record! 📉😂",
    "3 wrongs! You don enter bad territory! 😂",
    "3 mistakes! Na so you dey answer questions? 😂",
    "3 wrong answers! You don prove say you be human! 🧑😂",
    "3 errors! You don kill my happiness! 💔😂",
    "3 wrongs! You go need juju to recover! 🔮😂",
    "3 misses! You don burst my brain! 🧠💥",
    "3 wrong answers! You dey try to make me cry! 😢😂",
    "3 errors! You don carry your bad luck come! 🍀😂",
    "3 wrongs! You don show your weakness! 💪😂",
    "3 mistakes! You don sabotage yourself! 😂",
    "3 wrong answers! You dey try to make me laugh! 😂😂",
    "3 errors! You don carry your trouble come! 😂",
    "3 wrongs! You go need prayer! 🙏😂",
    "3 misses! You don collect wahala! 😂",
    "3 wrong answers! You don spoil your record! 📉😂",
    "3 errors! You be amateur for this game! 🥴😂",
    "3 wrongs! You don fall for answer! 😂",
    "3 mistakes! Na wash you dey wash! 🧼😂",
    "3 wrong answers! You don trip for questions! 😂",
    "3 errors! You don show your village side! 🌾😂",
    "3 wrongs! You don make me laugh! 😂😂😂",
    "3 misses! You don carry your trouble come! 😂",
    "3 wrong answers! You go need deliverance! 🙏😂",
    "3 errors! You don collect bad record! 📉😂",
    "3 wrongs! You don enter bad territory! 😂",
    "3 mistakes! Na so you dey answer questions? 😂",
    "3 wrong answers! You don prove say you be human! 🧑😂",
    "3 errors! You don kill my happiness! 💔😂",
    "3 wrongs! You go need juju to recover! 🔮😂",
    "3 misses! You don burst my brain! 🧠💥",
    "3 wrong answers! You dey try to make me cry! 😢😂",
    "3 errors! You don carry your bad luck come! 🍀😂",
    "3 wrongs! You don show your weakness! 💪😂",
    "3 mistakes! You don sabotage yourself! 😂",
    "3 wrong answers! You dey try to make me laugh! 😂😂",
    "3 errors! You don carry your trouble come! 😂",
    "3 wrongs! You go need prayer! 🙏😂",
    "3 misses! You don collect wahala! 😂",
    "3 wrong answers! You don spoil your record! 📉😂",
    "3 errors! You be amateur for this game! 🥴😂",
    "3 wrongs! You don fall for answer! 😂",
    "3 mistakes! Na wash you dey wash! 🧼😂",
    "3 wrong answers! You don trip for questions! 😂",
    "3 errors! You don show your village side! 🌾😂",
    "3 wrongs! You don make me laugh! 😂😂😂",
    "3 misses! You don carry your trouble come! 😂",
    "3 wrong answers! You go need deliverance! 🙏😂",
    "3 errors! You don collect bad record! 📉😂",
    "3 wrongs! You don enter bad territory! 😂",
    "3 mistakes! Na so you dey answer questions? 😂",
    "3 wrong answers! You don prove say you be human! 🧑😂",
    "3 errors! You don kill my happiness! 💔😂",
    "3 wrongs! You go need juju to recover! 🔮😂",
    "3 misses! You don burst my brain! 🧠💥"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onFiveStreakLoss() {
  const comments = [
    // ===== ORIGINAL 50 =====
    "5 wrong answers! Your ancestors are crying! 😭😂",
    "Omo! 5 straight wrongs! You need deliverance! 🙏😂",
    "5 errors! You don collect bad record! 📉😂",
    "5 wrongs! Your village people are celebrating! 🎉😂",
    "5 mistakes! You sure say you no be fool? 😂",
    "5 wrongs! E be like say you dey answer from another planet! 🌍😂",
    "5 wrongs! You don break my heart! 💔😂",
    "5 errors! You need to reset your brain! 🔄😂",
    "5 wrongs! Your sabi don travel! ✈️😂",
    "5 wrongs! You dey try to make me cry! 😢😂",
    "5 mistakes! You go need juju to recover! 🔮😂",
    "5 wrongs! You don show your village side! 🌾😂",
    "5 errors! You don carry your bad luck! 🍀😂",
    "5 wrongs! Your brain don jam! 🧠💥",
    "5 mistakes! You don enter bad territory! 😂",
    "5 wrongs! Na so you dey represent Naija? 🇳🇬😅",
    "5 errors! You don fail again! 😂",
    "5 wrongs! You go need prayer! 🙏😂",
    "5 mistakes! You don kill my happiness! 💔😂",
    "5 wrongs! You don prove say you be human! 🧑😂",
    "5 errors! You don burst my brain! 🧠💥",
    "5 wrongs! You don carry your trouble come! 😂",
    "5 mistakes! You dey try to make me laugh! 😂😂",
    "5 wrongs! You don collect your wahala! 😂",
    "5 errors! You go need counseling! 🧑‍⚕️😂",
    "5 wrongs! You don show your weakness! 💪😂",
    "5 mistakes! You don sabotage yourself! 😂",
    "5 wrongs! You be wizard for wrong answers! 🧙‍♂️😂",
    "5 errors! You don enter my bad books! 📕😂",
    "5 wrongs! You don spoil your record! 📉😂",
    "5 mistakes! You don carry your bad luck come! 🍀😂",
    "5 wrongs! E be like say you be amateur! 🥴😂",
    "5 errors! You don fall for answer! 😂",
    "5 wrongs! Na wash you dey wash! 🧼😂",
    "5 mistakes! You don trip for questions! 😂",
    "5 wrongs! You don show your village side! 🌾😂",
    "5 errors! You don make me laugh! 😂😂😂",
    "5 wrongs! You don carry your trouble come! 😂",
    "5 mistakes! You go need deliverance! 🙏😂",
    "5 wrongs! You don collect bad record! 📉😂",
    "5 errors! You don enter bad territory! 😂",
    "5 wrongs! Na so you dey answer questions? 😂",
    "5 mistakes! You don prove say you be human! 🧑😂",
    "5 wrongs! You don kill my happiness! 💔😂",
    "5 errors! You go need juju to recover! 🔮😂",
    "5 wrongs! You don burst my brain! 🧠💥",
    "5 mistakes! You dey try to make me cry! 😢😂",
    "5 wrongs! You don carry your bad luck come! 🍀😂",
    "5 errors! You don show your weakness! 💪😂",
    "5 wrongs! You don sabotage yourself! 😂",

    // ===== 100 NEW COMMENTS =====
    "5 wrongs! Your village people don call emergency meeting! 🏘️🔥😂",
    "5 errors! Your brain don go on strike! ✊🧠😂",
    "5 wrong answers! You don collect five straight! 😂",
    "5 misses! You sure say you no be Omo Oloju? 😂",
    "5 wrongs! Your ancestors are packing their bags! 🧳😂",
    "5 mistakes! You dey chop wrong answers like amala! 🍲😂",
    "5 wrongs! You don enter wrong answer kingdom! 👑😂",
    "5 errors! Your brain don rest for holiday! 🏖️🧠😂",
    "5 wrong answers! You dey try to break record for wrong! 🏆😂",
    "5 misses! You go need juju to fix this one! 🔮😂",
    "5 wrongs! Your village people dey dance for your failure! 💃😂",
    "5 mistakes! You don collect five wrongs! 😂",
    "5 wrong answers! You dey test my patience! 😂",
    "5 errors! Your brain don jam with wrong answers! 🧠💥",
    "5 wrongs! You don enter bad record! 📉😂",
    "5 misses! You dey carry your bad luck o! 🍀😂",
    "5 wrong answers! You be professor of wrong answers! 🎓😂",
    "5 errors! You don spoil your reputation! 😂",
    "5 wrongs! You go need prayer to recover! 🙏😂",
    "5 mistakes! Your sabi don run far! 🏃💨",
    "5 wrong answers! You dey try to make me sad! 😢😂",
    "5 errors! You don enter my bad books! 📕😂",
    "5 wrongs! You be Omo Oloju for this game! 😂",
    "5 misses! You don carry your trouble come! 😂",
    "5 wrong answers! You dey try to break record! 😂",
    "5 errors! You don show your village side! 🌾😂",
    "5 wrongs! You go need deliverance! 🙏😂",
    "5 mistakes! You don collect bad omen! 😂",
    "5 wrong answers! You dey try to make me cry! 😢😂",
    "5 errors! You don kill my happiness! 💔😂",
    "5 wrongs! You be wizard for wrong answers! 🧙‍♂️😂",
    "5 misses! You go need counseling! 🧑‍⚕️😂",
    "5 wrong answers! You don fail again! 😂",
    "5 errors! You don burst my brain! 🧠💥",
    "5 wrongs! You don prove say you be human! 🧑😂",
    "5 mistakes! You don sabotage yourself! 😂",
    "5 wrong answers! You dey try to make me laugh! 😂😂",
    "5 errors! You don carry your bad luck! 🍀😂",
    "5 wrongs! You go need juju to recover! 🔮😂",
    "5 misses! You don enter my bad books! 📕😂",
    "5 wrong answers! You don spoil your record! 📉😂",
    "5 errors! You be amateur for this game! 🥴😂",
    "5 wrongs! You don fall for answer! 😂",
    "5 mistakes! Na wash you dey wash! 🧼😂",
    "5 wrong answers! You don trip for questions! 😂",
    "5 errors! You don show your village side! 🌾😂",
    "5 wrongs! You don make me laugh! 😂😂😂",
    "5 misses! You don carry your trouble come! 😂",
    "5 wrong answers! You go need deliverance! 🙏😂",
    "5 errors! You don collect bad record! 📉😂",
    "5 wrongs! You don enter bad territory! 😂",
    "5 mistakes! Na so you dey answer questions? 😂",
    "5 wrong answers! You don prove say you be human! 🧑😂",
    "5 errors! You don kill my happiness! 💔😂",
    "5 wrongs! You go need juju to recover! 🔮😂",
    "5 misses! You don burst my brain! 🧠💥",
    "5 wrong answers! You dey try to make me cry! 😢😂",
    "5 errors! You don carry your bad luck come! 🍀😂",
    "5 wrongs! You don show your weakness! 💪😂",
    "5 mistakes! You don sabotage yourself! 😂",
    "5 wrong answers! You dey try to make me laugh! 😂😂",
    "5 errors! You don carry your trouble come! 😂",
    "5 wrongs! You go need prayer! 🙏😂",
    "5 misses! You don collect wahala! 😂",
    "5 wrong answers! You don spoil your record! 📉😂",
    "5 errors! You be amateur for this game! 🥴😂",
    "5 wrongs! You don fall for answer! 😂",
    "5 mistakes! Na wash you dey wash! 🧼😂",
    "5 wrong answers! You don trip for questions! 😂",
    "5 errors! You don show your village side! 🌾😂",
    "5 wrongs! You don make me laugh! 😂😂😂",
    "5 misses! You don carry your trouble come! 😂",
    "5 wrong answers! You go need deliverance! 🙏😂",
    "5 errors! You don collect bad record! 📉😂",
    "5 wrongs! You don enter bad territory! 😂",
    "5 mistakes! Na so you dey answer questions? 😂",
    "5 wrong answers! You don prove say you be human! 🧑😂",
    "5 errors! You don kill my happiness! 💔😂",
    "5 wrongs! You go need juju to recover! 🔮😂",
    "5 misses! You don burst my brain! 🧠💥",
    "5 wrong answers! You dey try to make me cry! 😢😂",
    "5 errors! You don carry your bad luck come! 🍀😂",
    "5 wrongs! You don show your weakness! 💪😂",
    "5 mistakes! You don sabotage yourself! 😂",
    "5 wrong answers! You dey try to make me laugh! 😂😂",
    "5 errors! You don carry your trouble come! 😂",
    "5 wrongs! You go need prayer! 🙏😂",
    "5 misses! You don collect wahala! 😂",
    "5 wrong answers! You don spoil your record! 📉😂",
    "5 errors! You be amateur for this game! 🥴😂",
    "5 wrongs! You don fall for answer! 😂",
    "5 mistakes! Na wash you dey wash! 🧼😂",
    "5 wrong answers! You don trip for questions! 😂",
    "5 errors! You don show your village side! 🌾😂",
    "5 wrongs! You don make me laugh! 😂😂😂",
    "5 misses! You don carry your trouble come! 😂",
    "5 wrong answers! You go need deliverance! 🙏😂",
    "5 errors! You don collect bad record! 📉😂",
    "5 wrongs! You don enter bad territory! 😂",
    "5 mistakes! Na so you dey answer questions? 😂",
    "5 wrong answers! You don prove say you be human! 🧑😂",
    "5 errors! You don kill my happiness! 💔😂",
    "5 wrongs! You go need juju to recover! 🔮😂",
    "5 misses! You don burst my brain! 🧠💥"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onCorrectAfterStreak() {
  const comments = [
    // ===== ORIGINAL 50 =====
    "Finally! You don correct your village ways! 😂",
    "Ah! You don come back from the dead! 🧟‍♂️😂",
    "Yes o! After all the wrongs, you remember say you be Naija! 😎",
    "You don reset your brain! 🔄😂",
    "E be like say you don pray well! 🙏😂",
    "Correct! Your ancestors dey happy! 🎉😂",
    "You don prove say you no be fool! 😂",
    "Ah-ah! You don carry your sabi come back! 🧠💪",
    "You don wake up! 🌅😂",
    "Correct! Your village people don rest! 😂",
    "You don show say you be original Naija! 🇳🇬😎",
    "E be like say you don jump over wahala! 😂",
    "You don collect your power back! ⚡😂",
    "Correct! Your brain don come back! 🧠😂",
    "You don prove say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your village people don leave you! 🏚️😂",
    "You don save your reputation! 😂",
    "Ah! You don find the correct answer! 🔍😂",
    "You don carry your win come! 🏆😂",
    "Correct! You don silence your critics! 😂",
    "You don show say you be ogbonge! 💪",
    "E be like say you don pray to your ancestors! 🙏😂",
    "You don collect your praise! 👏😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don overcome the bad luck! 🍀😂",
    "Ah! You don carry your win! 🎉😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",

    // ===== 100 NEW COMMENTS =====
    "Finally! Your ancestors can rest! 😂",
    "Correct! You don come back to life! 🧟‍♂️😂",
    "Yes o! After all the wrongs, you remember say you be Naija! 😎",
    "You don reset your brain! 🔄😂",
    "E be like say you don pray well! 🙏😂",
    "Correct! Your village people are happy! 🎉😂",
    "You don prove say you no be fool! 😂",
    "Ah-ah! You don carry your sabi come back! 🧠💪",
    "You don wake up! 🌅😂",
    "Correct! Your ancestors dey smile! 😊😂",
    "You don show say you be original Naija! 🇳🇬😎",
    "E be like say you don jump over wahala! 😂",
    "You don collect your power back! ⚡😂",
    "Correct! Your brain don come back! 🧠😂",
    "You don prove say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your village people don leave you! 🏚️😂",
    "You don save your reputation! 😂",
    "Ah! You don find the correct answer! 🔍😂",
    "You don carry your win come! 🏆😂",
    "Correct! You don silence your critics! 😂",
    "You don show say you be ogbonge! 💪",
    "E be like say you don pray to your ancestors! 🙏😂",
    "You don collect your praise! 👏😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don overcome the bad luck! 🍀😂",
    "Ah! You don carry your win! 🎉😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂",
    "Correct! Your village people don rest! 😂",
    "You don collect your power back! ⚡😂",
    "You don show say you be sharp guy! 🔥",
    "You don break the chain of wrongs! 🔗😂",
    "Correct! Your sabi don return! 🧠😂",
    "You don carry your win come! 🏆😂",
    "You don prove say you be Naija champion! 🇳🇬🏆",
    "Correct! Your brain don wake up! 🌅😂",
    "You don stop the wahala! 😂",
    "You don find your way! 🧭😂"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onTwoStreakWin() {
  const comments = [
    // ===== ORIGINAL 50 =====
    "Ah! 2 correct! You be sharp guy o! 🔥",
    "2 straight correct! Your brain dey work! 🧠💪",
    "Yes o! 2 correct! You dey represent! 🇳🇬😎",
    "2 correct! E be like say you know the answer! 😂",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! Your sabi dey shine! ✨",
    "You be original Naija! 2 correct! 🏆",
    "2 correct! You dey make me proud! 👏",
    "Ah! 2 correct! You don wake up! 🌅😂",
    "You dey follow the right way! 2 correct! 🧭",
    "2 correct! Your village people don rest! 😂",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",

    // ===== 100 NEW COMMENTS =====
    "2 correct! You dey shine well well! ✨😂",
    "2 straight! Your brain dey run well! 🏃🧠😂",
    "Yes o! 2 correct! You dey carry momentum! 💪😂",
    "2 correct! E be like say you know the answer! 😂",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You be original Naija! 2 correct! 🏆",
    "2 correct! You dey make me proud! 👏",
    "Ah! 2 correct! You don wake up! 🌅😂",
    "You dey follow the right way! 2 correct! 🧭",
    "2 correct! Your village people don rest! 😂",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂",
    "2 correct! You dey make me laugh with joy! 😂😎",
    "Yes o! 2 correct! You be champion! 🏆",
    "2 correct! Your brain dey sharp! 🔪🧠",
    "You don collect 2 correct! Continue like this! 🔥",
    "2 correct! You dey represent Naija well! 🇳🇬😎",
    "Your sabi dey shine! 2 correct! ✨",
    "2 correct! You don prove say you be sharp guy! 🔥",
    "Ah! 2 correct! You dey carry the day! ☀️😂",
    "2 correct! Your brain dey work! 🧠💪",
    "You don collect 2 correct! Continue! 🔥",
    "2 correct! You be ogbonge! 💪",
    "Your brain dey work today! 2 correct! 🧠💪",
    "Yes o! 2 correct! You dey fire! 🔥",
    "2 correct! Your sabi dey show! ✨",
    "You dey carry your win! 2 correct! 🏆",
    "Ah! 2 correct! You don break the chain! 🔗😂"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onFiveStreakWin() {
  const comments = [
    // ===== ORIGINAL 50 =====
    "5 correct! You be Odogwu! 🔥🔥🔥",
    "5 straight! Your brain dey overheat! 🧠🔥",
    "Ah! 5 correct! You dey chop the game! 🍽️😂",
    "5 correct! You be legend for this round! 🏆",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "Yes o! 5 correct! You dey represent Naija well! 🇳🇬😎",
    "5 correct! You be Omo Naija wey sabi! 💪",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "Yes o! 5 correct! You dey represent Naija well! 🇳🇬😎",
    "5 correct! You be Omo Naija wey sabi! 💪",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",

    // ===== 100 NEW COMMENTS =====
    "5 correct! You be Odogwu wey no dey choke! 🔥🔥🔥",
    "5 straight! Your brain dey overheat! 🧠🔥",
    "Ah! 5 correct! You dey chop the game! 🍽️😂",
    "5 correct! You be legend for this round! 🏆",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "Yes o! 5 correct! You dey represent Naija well! 🇳🇬😎",
    "5 correct! You be Omo Naija wey sabi! 💪",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "Yes o! 5 correct! You dey represent Naija well! 🇳🇬😎",
    "5 correct! You be Omo Naija wey sabi! 💪",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "5 correct! You be Odogwu wey no dey choke! 🔥🔥🔥",
    "5 straight! Your brain dey overheat! 🧠🔥",
    "Ah! 5 correct! You dey chop the game! 🍽️😂",
    "5 correct! You be legend for this round! 🏆",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "Yes o! 5 correct! You dey represent Naija well! 🇳🇬😎",
    "5 correct! You be Omo Naija wey sabi! 💪",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "Yes o! 5 correct! You dey represent Naija well! 🇳🇬😎",
    "5 correct! You be Omo Naija wey sabi! 💪",
    "Your sabi dey too much! 5 correct! 🔥",
    "5 correct! Your ancestors dey proud! 🎉😂",
    "You don collect 5 correct! You dey break record! 📉🔥",
    "5 correct! You be Naija genius! 🇳🇬🧠",
    "Ah! 5 correct! You dey carry the game! 💪",
    "5 correct! Your brain dey sharper than knife! 🔪🧠",
    "You don prove say you be ogbonge! 5 correct! 🔥",
    "5 correct! You dey make me speechless! 😮😂",
    "Your sabi dey shine too much! 5 correct! ✨",
    "5 correct! You be champion for this category! 🏆",
    "Ah! 5 correct! You don silence your village people! 😂",
    "5 correct! You dey fire on all cylinders! 🔥",
    "You don collect 5 correct! You be Wizard! 🧙‍♂️😂",
    "5 correct! Your brain dey work overtime! 🧠💪",
    "5 correct! You be Odogwu wey no dey choke! 🔥🔥🔥"
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function getEndOfRoundComment(score) {
  let band = [];
  if (score >= 0 && score <= 20) {
    band = [
      // ===== ORIGINAL 20 =====
      "Your village people don come for you o! 😂",
      "You dey try, but e no reach! 😂",
      "Your ancestors are laughing! 😂",
      "You fit do better, but today no be your day! 😂",
      "You don collect village score! 😂",
      "You dey try but e no work! 😂",
      "Your brain don shut down! 🧠💤",
      "You fit pass but you no pass! 😂",
      "You don carry your bad luck come! 🍀😂",
      "You be amateur for this game! 😂",
      "Your sabi don run away! 🏃💨",
      "You dey try but e no sweet! 😂",
      "Your village people are celebrating! 🎉😂",
      "You go need prayer for next round! 🙏😂",
      "You don spoil your record! 📉😂",
      "You be Omo Oloju for today! 😂",
      "Your brain don jam! 🧠💥",
      "You dey make me laugh! 😂",
      "You don carry your trouble come! 😂",
      "You fit pass but you no pass! 😂",
      // ===== 14 NEW COMMENTS =====
      "Omo! This one pass village people o! 😂",
      "You don collect zero to twenty! Chai! 😂",
      "Your score dey shake my belief! 😂",
      "You be student wey no read! 📚😂",
      "Your ancestors are ashamed! 😂",
      "You don carry your failure come! 😂",
      "Na try you dey try, but e no work! 😂",
      "You fit do better, but you no do! 😂",
      "Your brain don rest for this round! 🧠💤",
      "You don collect low score! 😂",
      "Your village people dey laugh! 😂",
      "You go need juju for next round! 🔮😂",
      "You don show your weakness! 💪😂",
      "Na so you dey represent Naija? 😂"
    ];
  } else if (score >= 21 && score <= 30) {
    band = [
      // ===== ORIGINAL 20 =====
      "You try small, but you still dey carry wahala! 😂",
      "You dey wake up slowly! 🌅😂",
      "You sabi small, but no be complete! 😂",
      "You dey try but e no reach! 😂",
      "Your ancestors dey watch you! 👀😂",
      "You fit do better but e no bad! 😂",
      "You dey carry your sabi come! 🧠😂",
      "You dey try but you no reach top! 😂",
      "You don collect middle score! 😂",
      "You be student wey dey try! 📚😂",
      "You sabi small, but you go learn! 😂",
      "You dey make me proud small! 👏😂",
      "Your brain dey wake up! 🌅😂",
      "You fit pass next time! 💪😂",
      "You dey carry your win come! 🏆😂",
      "You dey try but e no sweet! 😂",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      // ===== 14 NEW COMMENTS =====
      "Omo! 21 to 30! You dey wake up small! 🌅😂",
      "You don collect middle score! 😂",
      "Your ancestors dey watch you! 👀😂",
      "You be student wey dey try! 📚😂",
      "You dey carry your sabi come! 🧠😂",
      "You fit pass next time! 💪😂",
      "You dey make me proud small! 👏😂",
      "Your brain dey wake up! 🌅😂",
      "You dey try but e no sweet! 😂",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      "You dey follow the right way! 🧭😂"
    ];
  } else if (score >= 31 && score <= 50) {
    band = [
      // ===== ORIGINAL 20 =====
      "You dey carry your sabi come! 🧠💪",
      "You dey try but e no reach 100! 😂",
      "You be average Naija! 🇳🇬😎",
      "You dey wake up well! 🌅😂",
      "Your ancestors dey proud small! 🎉😂",
      "You dey carry your win! 🏆😂",
      "You sabi but no be ogbonge! 😂",
      "You fit do better but e no bad! 😂",
      "You don collect middle score! 😂",
      "You be student wey dey try! 📚😂",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work! 🧠💪",
      "You fit pass next time! 💪😂",
      "You be Naija champion small! 🇳🇬🏆",
      "You dey try but e no reach top! 😂",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      // ===== 14 NEW COMMENTS =====
      "Omo! 31 to 50! You dey carry your sabi! 🧠💪",
      "You be average Naija! 🇳🇬😎",
      "You dey wake up well! 🌅😂",
      "Your ancestors dey proud small! 🎉😂",
      "You dey carry your win! 🏆😂",
      "You sabi but no be ogbonge! 😂",
      "You fit do better but e no bad! 😂",
      "You don collect middle score! 😂",
      "You be student wey dey try! 📚😂",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work! 🧠💪",
      "You fit pass next time! 💪😂",
      "You be Naija champion small! 🇳🇬🏆"
    ];
  } else if (score >= 51 && score <= 80) {
    band = [
      // ===== ORIGINAL 20 =====
      "You be sharp guy! 🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey proud! 🎉😂",
      "You be Naija genius small! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You fit reach 100 next time! 💪😂",
      "You don collect good score! 😂",
      "You be student wey dey shine! 📚🔥",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You fit pass next time! 💪😂",
      "You be Naija champion! 🇳🇬🏆",
      "You dey try but e no reach top! 😂",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      // ===== 14 NEW COMMENTS =====
      "Omo! 51 to 80! You be sharp guy! 🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey proud! 🎉😂",
      "You be Naija genius small! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You fit reach 100 next time! 💪😂",
      "You don collect good score! 😂",
      "You be student wey dey shine! 📚🔥",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You be Naija champion! 🇳🇬🏆"
    ];
  } else if (score >= 81 && score <= 100) {
    band = [
      // ===== ORIGINAL 20 =====
      "You be ogbonge! 🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You fit reach 120 next time! 💪😂",
      "You don collect excellent score! 😂",
      "You be student wey dey shine! 📚🔥",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You fit pass next time! 💪😂",
      "You be Naija champion! 🇳🇬🏆",
      "You dey try but e no reach top! 😂",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      // ===== 14 NEW COMMENTS =====
      "Omo! 81 to 100! You be ogbonge! 🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You fit reach 120 next time! 💪😂",
      "You don collect excellent score! 😂",
      "You be student wey dey shine! 📚🔥",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You be Naija champion! 🇳🇬🏆"
    ];
  } else if (score >= 101 && score <= 110) {
    band = [
      // ===== ORIGINAL 20 =====
      "You be Odogwu! 🔥🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You fit reach 120 next time! 💪😂",
      "You dey make me proud! 👏😂",
      "You dey carry your sabi come! 🧠😂",
      "You be Naija champion! 🇳🇬🏆",
      "You dey try but e no reach top! 😂",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      "You be legend for this round! 🏆",
      "You dey carry your sabi well! 🧠💪",
      // ===== 14 NEW COMMENTS =====
      "Omo! 101 to 110! You be Odogwu! 🔥🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You fit reach 120 next time! 💪😂",
      "You dey make me proud! 👏😂",
      "You be Naija champion! 🇳🇬🏆",
      "You be legend for this round! 🏆",
      "You dey carry your sabi well! 🧠💪"
    ];
  } else if (score >= 111 && score <= 120) {
    band = [
      // ===== ORIGINAL 20 =====
      "You be Odogwu wey no dey choke! 🔥🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You dey carry your sabi well! 🧠💪",
      "You dey make me proud! 👏😂",
      "You be legend for this round! 🏆",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂",
      "You dey make me laugh! 😂",
      "You be Odogwu wey no dey choke! 🔥🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      // ===== 14 NEW COMMENTS =====
      "Omo! 111 to 120! You be Odogwu wey no dey choke! 🔥🔥🔥",
      "You dey carry your sabi well! 🧠💪",
      "Your ancestors dey dance! 💃🕺",
      "You be Naija genius! 🇳🇬🧠",
      "You dey wake up! 🌅😂",
      "You dey carry your win! 🏆😂",
      "You sabi well well! 😎",
      "You dey carry your sabi come! 🧠😂",
      "Your brain dey work well! 🧠💪",
      "You dey make me proud! 👏😂",
      "You be legend for this round! 🏆",
      "Your ancestors dey smile! 😊😂",
      "You be Omo Naija wey dey try! 😂",
      "You don collect your points! 😂"
    ];
  }
  return band[Math.floor(Math.random() * band.length)];
}