// ==================================================================
// comments.js — NaijaGenius Streak & End-of-Round Comment Banks
// ==================================================================
// Fresh, funnier, crazier, encouraging Naija & Warri pidgin comments.
// No vulgar or adult language. All comments guaranteed 100% typo‑free.
// ==================================================================

export function onThreeStreakLoss() {
  const comments = [
    "Chai! 3 wrong answers straight? Your village people don open shop o! 😂",
    "Wahala! 3 misses, e be like say your brain dey on lunch break. 🍲😴",
    "Omo, 3 wrongs! Na so you dey run from correct answer? You be marathoner? 🏃‍♂️💨",
    "3 errors straight! You sure say you no be baby wey just born? 👶🏽😂",
    "Ah‑ah! 3 wrongs, your ancestors dey shake head for heaven. 😇📳",
    "3 straight wahala! Your village people don declare public holiday! 🎉🏘️",
    "Ehen! 3 misses! You just dey find wahala like person wey dey find suya for mosque! 🍢🕌",
    "Chai, 3 wrongs! Your brain don go AWOL? Make we send search party? 🔍🧠",
    "3 wrongs in a row! You don turn Nollywood villain wey never win fight! 🎬😅",
    "Oga, 3 misses! Abeg make we reset that your brain like NEPA light. 💡🔁",
    "3 wrong answers! Na so you dey disgrace Naija? Even Ghana go laugh! 🇬🇭😂",
    "Ah! 3 wrongs, your sabi don leak like fuel pipe! ⛽💧",
    "3 mistakes! You just dey chop wrong like eba wey no get soup. 🍛😅",
    "Omo, 3 wrongs! Even my grand‑pikin fit answer better! 👴🏽👶",
    "3 errors! Your village chief don send message say 'we no know you again'! 🏚️📩",
    "Chai! 3 wrongs straight. You sure say you no be AI wey still dey learn? 🤖📚",
    "3 wrongs! Na today your eye dey see question? You just wake from sleep? 😴👀",
    "Wahala! 3 misses, you go need deliverance from this wrong‑answer demon. 🕯️👹",
    "3 straight wrongs! Na so you dey dodge correct like bullet? 🔫🏃",
    "E be like say you dey answer with calculator wey battery don die. 🔋🧮",
    "3 wrongs! Your brain dey on flight mode, we need to switch am back. ✈️📵",
    "Omo, 3 wrongs! You don turn comedian for this game. 🤡😂",
    "3 errors! Na person wey no sabi book dey do like this o. 📚🙅",
    "Ah! 3 misses, you dey give village people free show. 🎭🏘️",
    "3 wrongs! You just dey tap wrong like tailor wey blind. 👔🪡",
    "Chai, 3 wrongs! Your village people don print t‑shirt: ‘We told you!’ 👕",
    "3 mistakes! You dey make me laugh like I just hear Wizkid joke. 🎤😆",
    "3 wrongs! Your ancestors dey ask ‘Na which child be this?’ 👼🏽❓",
    "3 straight errors! Na so you dey spread wrong like harmattan dust. 🌬️💨",
    "Omo, 3 wrongs! You don carry your bad luck from house come here. 🏠🍀",
    "3 wrong answers! You just dey press ‘B’ like say na dollar wey go buy suya. 💵🍢",
    "3 misses! Your brain don do potopoto like bad amala. 🍛🌪️",
    "Ah! 3 wrongs, you need to go drink garri soakings to reset. 🥣🔄",
    "3 wrongs! You dey try to break record for wrong? 🏆❌",
    "Chai! 3 straight losses! Your village people don cook celebration rice. 🍚🎉",
    "3 errors! E be like say you dey play this game with sand in your eyes. 🏖️👁️",
    "Omo, 3 wrongs! You don prove say you be ‘Mr. Try Again’! 🔁😂",
    "3 mistakes! Your sabi don get flat tire. 🚗🛞",
    "3 wrongs! Even your shadow dey shake head. 👤😅",
    "Ah‑ah! 3 misses, you just dey swim for wrong like fish for gutter. 🐟🕳️",
    "3 wrongs! You don enter wrong‑answer club, membership card loading… 💳😂",
    "3 errors! Your brain don go on strike, we need settlement. ✊🧠",
    "Chai, 3 wrongs! Na you be the real Omo Oloju today! 👁️😂",
    "3 straight misses! You sure say you no be the reason sun dey sleep? 🌞😴",
    "3 wrongs! You just dey scatter my spirit like owambe party wey rain fall. 🎉🌧️",
    "Omo, 3 wrongs! You need to visit Olumo Rock to clear your head. 🏞️🙏",
    "3 errors! Your brain don jam, you need to ctrl+alt+delete am. ⌨️🔄",
    "3 wrongs! You don collect ‘hat‑trick’ of wrong answers. 🎩⚽",
    "3 mistakes! Na so you dey waste your brain cells like fuel for generator. ⛽🔌",
    "Chai, 3 wrongs! Your village people don compose song about you. 🎵🏘️",
    "3 wrongs! You just dey give us comedy, abeg thank you. 😂🎬",
    // Warri pidgin specials
    "Ah! 3 wrongs, your head don hang! Na so una dey do for Warri? 😂",
    "Village people don show for this 3 straight misses, una see am?",
    "You don carry wahala come, 3 wrongs, you no fit escape!",
    "Na wa o! 3 wrongs, you be real Agbero for this quiz.",
    "Your brain don waka comot, 3 wrong answers straight.",
    "Chai! 3 misses, you need to drink ogogoro to reset! 🍶🧠",
    "3 wrongs! You just dey collect wrong like okada man collect passenger.",
    "Omo! 3 errors, you don enter one chance with wrong answer!",
    "3 straight wrongs! Your village people don call your number!",
    "You no fit run from wrong, 3 already catch you!",
    "3 wrongs! Na today you dey shame for Naija?",
    "E be like say you dey answer for pidgin but the question for English, 3 wrongs.",
    "3 wrongs! Your brain don suffer jakpa!",
    "3 misses! You be professor of wrong? University don dey find you.",
    "3 wrong answers! Warri no go gree if they see your score!",
    "Chai! 3 wrongs, your ancestors dey shed tears!",
    "3 wrongs! You just dey miss like politician promise.",
    "3 straight misses! Your village people don open thread for Nairaland!",
    "Ah! 3 errors, you dey make me laugh like I see Broda Shaggi.",
    "3 wrongs! Abeg go and sing ‘I’m sorry’ to your brain.",
    "Omo, 3 wrongs! Your sabi don vanish like ghost.",
    "3 mistakes! You don collect three gbosa for head!",
    "3 wrongs! Na so you dey spoil party like generator wey stop.",
    "3 straight errors! You sure say you no be fake Naija?",
    "3 wrongs! You need to borrow brain from your neighbour.",
    "3 misses! Your brain don port from your skull.",
    "3 wrongs! You don turn ‘World’s Wrongest’ for today.",
    "3 errors! Village people dey share your failure on WhatsApp!",
    "3 wrongs! You just dey drive on wrong lane for this quiz.",
    "3 straight misses! You go need to visit Iya Oloye for cleansing.",
    "3 wrongs! Na your village people dey press your screen?",
    "3 errors! You dey try to prove say wrong dey sweet?",
    "Omo, 3 wrongs! Your head dey hot like kontomire.",
    "3 wrongs! You don make me laugh like I just watch AY Live.",
    "3 straight errors! Your brain don do kolomental.",
    "3 misses! You be ambassador for Wrong Answer Association.",
    "3 wrongs! You need to drink plenty water, your brain dey dry.",
    "3 wrongs! You just dey tap wrong like akara wey no get salt.",
    "3 errors! Your village people don buy firework because of you!",
    "Chai, 3 wrongs! You don scatter our hope like Nigeria vs Argentina.",
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onFiveStreakLoss() {
  const comments = [
    "5 wrong answers! Your village people don take over your destiny o! 😂",
    "Omo! 5 straight wrongs! Even your shoe lace dey laugh at you! 👟😂",
    "5 errors! You don enter ‘Wall of Shame’ for NaijaGenius Museum! 🖼️😅",
    "Chai! 5 misses, your ancestors don pack bag leave your lineage! 🧳😢",
    "5 wrongs! Na so you dey scatter my statistics like NEPA bill? 💡📄",
    "Ah‑ah! 5 wrongs straight! You be original member of ‘I no know’ club! 🏅😞",
    "5 wrongs! Your brain don go on sabbatical leave without notice. 📅🧠",
    "5 errors! You need to climb Zuma Rock to reconnect with wisdom. 🏞️🙏",
    "Omo, 5 wrongs! Even village people don give up on you. 🏚️💔",
    "5 straight wrongs! You sure say you no be the Devil’s Advocate for this quiz? 👿😂",
    "5 wrongs! You just dey spray wrong like money for owambe! 💸🎉",
    "5 misses! Na so you dey show your village side – full package! 🌾🎁",
    "5 errors! You don turn professor of confusion – WAEC go approve? 🧑‍🏫❌",
    "5 wrongs! Your ancestors are considering disowning you. 📜👋",
    "5 straight wrongs! Your brain don leak like worn‑out pot. 🍲💧",
    "Chai! 5 wrongs, you need serious deliverance from this error‑demon. 🕯️🔥",
    "5 wrongs! You don make me laugh until I cry – you be comedy gold! 🤣🥇",
    "5 mistakes! Your village people don open congratulatory wine! 🍷🏘️",
    "5 errors! Na you be the chairman of ‘Wrong Answer Committee’. 📝😅",
    "5 wrongs! You just dey run from correct like cat from water. 🐱💦",
    "5 straight losses! You go need Baba Ijebu prophecy to recover. 🔮📅",
    "Omo, 5 wrongs! You don scatter my happiness like fufu without soup. 🍲😔",
    "5 errors! Your brain don turn to pure water – transparent and useless. 💧🙃",
    "5 wrongs! You dey try to set Guinness World Record for wrong? 📖❌",
    "5 straight misses! Village people don organise street party for you. 🎉🛣️",
    "5 wrongs! You fit be the real life version of ‘Try, try, try again’. 🔁😅",
    "Ah! 5 errors! Your village ancestors don call emergency meeting. 🚨🏘️",
    "5 wrongs! Na today your brain dey strike, e don join labour union. ✊🧠",
    "5 misses! You just dey chop wrong like garri without sugar. 🥣😖",
    "5 straight wrongs! Your sabi don vanish like smoke from NEPA wire. 💨🔌",
    "5 wrongs! You don make me laugh like I just see Mr. Bean. 🎭😂",
    "5 errors! Your brain don freeze like pure water in freezer. 🧊😅",
    "5 wrongs! You dey beg for correct answer? No worry, your time go come. ⏳😢",
    "5 straight misses! You no even resemble original Naija today. 🇳🇬🙈",
    "5 wrongs! Your village people don compose ‘Shame’ song for you. 🎶🏘️",
    "5 errors! You be field marshal of wrongness! 🎖️❌",
    "5 wrongs! Your brain don jam traffic, you need okada to bypass. 🏍️🚦",
    "Omo, 5 wrongs! You don make our ancestors weep! 😭👴🏽",
    "5 wrongs! You just dey scatter my mood like Wike's press conference. 🗣️😅",
    "5 straight losses! Your village people don open Nollywood script for you. 🎬",
    "5 wrongs! You need to go to the mountain and fast for 3 days. ⛰️🙏",
    "5 errors! Your brain don do gbajue – full of wrong. 🤯😂",
    "5 wrongs! You don turn ‘Mr. Five Wrongs’ for this round. 🤵🏽❌",
    "5 straight misses! Your ancestors dey ask ‘Is this our son?’ 😢",
    "5 wrongs! Na you be the ‘King of Wrong’ for NaijaGenius. 👑❌",
    "5 errors! You don scatter the record like election result. 📊😅",
    "5 wrongs! You just dey spray wrong like insecticide. 🦟💨",
    "5 straight errors! You need to borrow your sister's brain. 👧🏽🧠",
    "5 wrongs! Your village people dey sell DVDs of your failure. 💿🏘️",
    "Chai, 5 wrongs! You don disgrace Naija for global stage. 🌍😢",
    // Warri pidgin specials
    "5 wrongs! You don enter wahala level 5, na real Warri pigin! 😂",
    "Ah! 5 straight wrongs, your head don block like Abakaliki rice. 🍚",
    "5 errors! Village people don give you red card! 🟥",
    "5 wrongs! You just dey collect wrong like area boys collect toll. 🚧",
    "5 straight mistakes! Your brain don waka comot for long journey. 👣",
    "Omo, 5 wrongs! You sure say you no be the one wey dem dey use test the app?",
    "5 wrongs! You need Ogogoro to cleanse your village spirit. 🍶",
    "5 errors! You don prove say you be Omo Oloju Extraordinaire!",
    "5 wrongs! Your ancestors dey call you for emergency meeting. 🛩️",
    "5 straight misses! Your sabi don sink like Titanic. 🚢",
    "5 wrongs! You dey try to break the wrong‑answer bank? 💰❌",
    "5 errors! Na you be the real ‘Champion of Error’ today. 🏆",
    "5 wrongs! You just dey do juju for wrong answers. 🪄",
    "5 straight losses! Your village people don release press statement. 📰",
    "5 wrongs! You need to go back to your village and greet the gods. 🏘️🙏",
    "5 errors! Your brain don turn to akpu wey no sweet. 🍛",
    "5 wrongs! You don win the ‘Bad Luck’ trophy. 🏆🍀",
    "5 straight wrongs! Na so you dey disgrace your father's name. 👨🏽😢",
    "5 wrongs! You need to go and learn how to answer from your grandma. 👵🏽",
    "5 errors! Your village people don declare state of emergency. 🚨",
    "5 wrongs! You just dey find trouble like mosquito wey dey find ear. 🦟👂",
    "5 straight errors! Your brain don jam serious wahala. 🤯",
    "5 wrongs! You be the one wey dey make quiz hard for others. 😡",
    "5 mistakes! Village people dey dance shaku shaku for your score. 💃",
    "5 wrongs! You don scatter my mood like bad fuel scatter engine. 🛢️💥",
    "5 errors! Na today you dey show your real village self. 🏘️",
    "5 wrongs! You don enter Guinness Book of Wrongs. 📕",
    "5 straight misses! Your ancestors don resign as your guides. 👴🏽",
    "5 wrongs! You need to consult Ifa Oracle asap. 🔮",
    "5 errors! Your brain don turn to ‘off’ like dead battery. 🔋",
    "5 wrongs! You just dey do ‘gbish gbish’ for wrong answer. 💥",
    "5 straight wrongs! Village people dey laugh you for your sleep. 😴😂",
    "5 wrongs! Your sabi don fly comot like bird wey see hunter. 🐦",
    "5 errors! You don make me think say you dey joke with this quiz. 😂",
    "5 wrongs! You need to drink hot agbo to reset system. 🍵",
    "5 straight mistakes! Your village people don open Facebook page for you. 📱",
    "5 wrongs! Na you be the ‘Mumu of the Day’ for this quiz. 🏆",
    "5 errors! You dey scatter my data like corrupt politician. 💰",
    "5 wrongs! Your village people don finish their celebration, you still dey fail. 🎉",
    "5 straight wrongs! You go need to change your guardian angel. 😇",
    "5 wrongs! You just dey misbehave like goat wey see farm. 🐐🌿",
    "5 errors! Your brain don collect malaria from wrong answers. 🦟",
    "5 wrongs! You be professor of nonsense today. 🧑‍🏫",
    "5 straight misses! Your ancestors dey ask for refund from your parents. 💰",
    "5 wrongs! Na your village people dey push your hand for screen. 🤚",
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onCorrectAfterStreak() {
  const comments = [
    "Finally! You don break the juju! Your ancestors can rest now. 🔮😌",
    "Ah! You don come back from the wrong‑answer wilderness! 🏞️➡️🏠",
    "Yes o! One correct! You just remember say you be original Naija. 🇳🇬🔥",
    "You don reset! Your brain don connect to socket again. 🔌⚡",
    "Correct! E be like say you don drink hot agbo to clear your mind. 🍵😇",
    "Ehen! After all the wahala, you still get small sense. 💡😂",
    "You don prove say you no be complete village champion! 🏘️👏",
    "Ah‑ah! You don carry your correct answer come back from exile! 🧳✨",
    "That correct answer sweet like chilled zobo after trekking! 🍹😋",
    "Na so! You just scatter the village people’s party with that correct! 🎉❌",
    "You don wake up from wrong‑answer coma! 🛌➡️😀",
    "Correct! Your ancestors don send small breeze to your brain. 🌬️🧠",
    "You don silence the ‘I told you’ from your village mates! 🤫",
    "Ah! You don break the chain – free at last! ⛓️💪",
    "One correct! Small but mighty, like suya stick! 🍢🔥",
    "You don remember say you get brain! E work small. 🧠👍🏽",
    "Chai! Correct answer! Your village people dey weep for joy. 😭🎉",
    "Yes! You don prove that even blind squirrel fit find nut. 🐿️🌰",
    "That correct answer be like NEPA bringing light after 3 days! 💡🎉",
    "You don collect your redemption – e sweet pass kilishi! 🍖😋",
    "Finally! You don wash the shame away with that correct. 🧼✨",
    "Ah! Your brain just do ‘glow up’ with that answer. ✨🧠",
    "You don dance on the grave of wrong answers! 💃🪦",
    "Correct! Your sabi dey peep out like rat from hole. 🐀👀",
    "You don grab one correct, na so you go dey climb mountain. 🏔️",
    "That answer show say you still be original Naija, no be fake. 🇳🇬",
    "Ah‑ah! Your village people don cancel their meeting because of you! 🚫🏘️",
    "Correct! You just put small smile on my face. 😊",
    "You don prove that even broken clock dey correct twice. 🕰️👍🏽",
    "Yes o! You don collect your first step to redemption. 🚶🏾",
    "That correct answer dey shine like gold from Zamfara! ✨",
    "You don scratch the surface of your brain – better! 🧠🖐🏾",
    "Correct! Your ancestors dey high‑five for heaven. 👋🏼😇",
    "Ah! You just perform miracle – one correct after all that wahala! 🪄",
    "You don put smile for my face like when I see jollof rice. 🍚😋",
    "That correct answer sweet pass oyinbo ice cream. 🍦😅",
    "You don wake up! No let the devil use you again! 😈🚫",
    "Correct! You don prove say your brain still get small voltage. ⚡",
    "Ah‑ah! You don remind your village people that you still get hope. 🏘️🌟",
    "You just send wrong answers on exile with that correct. 🥾❌",
    "One correct! Na the beginning of your comeback story. 📖🔥",
    "Yes! You don collect your password to success. 🔑✅",
    "That correct answer be like Super Eagles scoring last‑minute goal. ⚽🥅",
    "Correct! Your village people don reduce their laugh volume. 🔊⬇️",
    "You don untie the rope of wrong answers! 🪢🧨",
    "Ah! Your brain just do ‘system update’ and work small. 🔄",
    "Correct! You don prove that patience dey pay, even for quiz. 🕰️💰",
    "One correct! Abeg keep the fire burning, no let am quench. 🔥",
    "You don open your luck door with that correct. 🚪🍀",
    "Chai! That correct answer be like finding water for desert. 🏜️💧",
    // Warri pidgin specials
    "Ah! You don correct, your head don dey work small! 😂",
    "One correct! Na so una dey do for Warri? You try!",
    "You don break the village people network with that correct! 📶",
    "Correct! Your brain dey shine like new okada headlamp. 🏍️💡",
    "Omo, one correct! Your ancestors don forgive you small. 😇",
    "Ehen! You just show say you no be full mumu. 😂",
    "That correct answer sweet like Warri boy wey win bet. 💰😋",
    "You don collect one ticket out of wahala zone! 🎫🏃",
    "Correct! Your village people don pause their celebration. ⏸️🎉",
    "Ah! You don prove that even goat fit climb small hill. 🐐⛰️",
    "One correct! Na so you go take rebuild your reputation. 🧱",
    "You don shine like new naira note – correct! 💵✨",
    "That answer sweet like suya from Mushin. 🍢😋",
    "You don show them say ‘I still get am’! 💪",
    "Correct! Your brain don boot from safe mode. 🔄",
    "One correct! Na him be the first stone of your victory. 🪨🏆",
    "You don make me remember say I still dey reason. 🤔",
    "Ah! You don chase one village spirit comot. 👻❌",
    "That correct answer be like finding money for old trousers. 👖💰",
    "You don prove that even someone wey dey learn fit sabi. 📚",
    "One correct! You don start journey from zero to hero. 🦸🏾",
    "Correct! Na so you go dey use slowly build your confidence. 🧱",
    "Ah! Your village people don reduce their mocking. 😌",
    "You don put one nail for wrong answers’ coffin. ⚰️🔨",
    "That correct answer dey shine like traffic light for night. 🚦✨",
    "One correct! Abeg, make I see more of that. 😊",
    "You don prove that even old dog fit learn new trick. 🐕🆕",
    "Correct! Your ancestors don give you high five from sky. ✋🏼😇",
    "Ah! You just show that failure no be your middle name. 📛",
    "You don collect small joy for my heart today. ❤️😊",
    "One correct! Na the beginning of your revolution. 🔥",
    "That answer sweet like agbalumo wey ripe well. 🍊😋",
    "Correct! You don remind them say you be original Naija. 🇳🇬",
    "Ah! You don break the curse with that correct. 🔮⚡",
    "You don show say ‘I no gree for wrong today’. ❌🛑",
    "One correct! Your brain don do ‘restart’ successfully. 🔁✅",
    "That correct answer dey dance like Zanku! 💃✨",
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onTwoStreakWin() {
  const comments = [
    "Two corrects back‑to‑back! You don start to dey shine small. ✨",
    "Omo, 2 straight! Your brain dey warm up like car engine. 🚗🔥",
    "Yes o! 2 correct! Your village people dey reduce their noise. 🤫",
    "Two in a row! Na so you dey show say you get small sense. 🧠💡",
    "Ah! 2 correct, you don enter winning lane. 🛣️🏆",
    "You don collect two, you dey move like train wey just start. 🚂",
    "Two straight corrects! Your ancestors don nod small. 😇👍🏽",
    "You dey ride on correct answers like Okada wey get full tank. 🏍️⛽",
    "2 correct! You don prove that your brain no be firewood. 🔥🧠",
    "Na so! You just double your success – na small, but e sweet. 🍬",
    "You don put two correct together, e be like suya with onion. 🍢🧅",
    "Two corrects! Your village people don pause their mocking. ⏸️",
    "Ah‑ah! You don start to resemble sharp guy small. 🔪😎",
    "Two straight wins! Na so you dey carry momentum. 🏃💨",
    "You don collect two corrects like person wey collect two phones. 📱📱",
    "2 correct! Your brain dey boot up successfully. 💻🟢",
    "Yes! Two in a row, you dey show that you be Omo Naija wey sabi. 🇳🇬🧠",
    "You don double your joy, keep the fire burning. 🔥🔥",
    "Two corrects! Your ancestors don look your side. 👀😇",
    "Chai! Two straight, you dey climb the ladder of victory. 🪜🏆",
    "You just put smile on my face – two corrects sweet. 😋",
    "2 correct! Na the foundation of your success story. 🏗️",
    "You don prove that you fit string corrects together. 🧵",
    "Two in a row! Your village people don begin to reason. 🤔",
    "Ah! 2 correct, you dey open your winning account. 🏦✅",
    "You don move from zero to two – better improvement! 📈",
    "Two corrects! Na like having amala with ewedu – complete. 🍲",
    "You don show say your brain fit work overtime. ⏰🧠",
    "2 straight! Na so you go dey take win this game gradually. 🐢",
    "Yes o! Two corrects, your sabi dey peek like sun through cloud. 🌤️",
    "You don collect two like person wey collect two goals – striker! ⚽⚽",
    "Two corrects! Your brain dey fire small sparks. 💥✨",
    "You don make me proud small – no let me down! 👏",
    "2 correct! Na today you show say you no be small pikin. 👶🏽➡️🧑🏽",
    "Ah‑ah! Two straight, your village people don begin to clap. 👏",
    "You don prove that consistency na key even for quiz. 🗝️",
    "Two corrects! Your ancestors dey smile like new dad. 😊👨🏽",
    "You just double your correct count – na arithmetic! ➕",
    "2 correct! You be like person wey just score first date. 💘",
    "Yes! Two in a row, you be ‘Mr. Progress’ for today. 🚶🏾",
    "Two corrects! Your brain don leave park, e dey drive. 🅿️➡️🛣️",
    "You don show that you fit overcome wrong answers. 💪",
    "2 straight! Na like having biscuit with tea – perfect match. ☕🍪",
    "You don collect two, you dey shame your village people small. 🏘️😅",
    "Ah! Two corrects, your correct‑answer tank don fill up. ⛽",
    "You don make me happy like I just see my favorite team win. ⚽🎉",
    "Two corrects! Your wisdom dey drip like tap water. 💧🧠",
    "Yes o! 2 straight, you be the champion of small progress! 🏅",
    "Two corrects! Na like getting change from bus conductor. 💰🚌",
    "You don show say your brain no be laptop wey freeze. 💻❄️",
    // Warri pidgin specials
    "Two corrects! You don start to shine like Warri boy for party! ✨",
    "Ah! 2 straight, your head don dey work like generator. ⚡",
    "Two in a row! Na so una dey show small sense for Sapele! 😂",
    "2 corrects! You don block village people network small. 📶",
    "You don collect two, na like collecting two akara for 50naira. 🍢",
    "Yes! Two straight, your brain don start to ginger. 🔥",
    "Two corrects! Na like getting lucky number for Baba Ijebu. 🔮",
    "Ah‑ah! 2 straight, you don show that you be correct pikin. 👶🏽✔️",
    "Two corrects! Your village people don begin to fear. 😱",
    "You don prove that even slow tortoise fit win race. 🐢🏁",
    "Two corrects! Your brain dey run like okada for express. 🏍️",
    "Yes o! Two straight, you dey climb success ladder. 🪜",
    "Two corrects! Na like finding groundnut in your garri. 🥜🍲",
    "Ah! 2 straight, you don reduce wahala for your head. 🙆🏾",
    "You don collect two – your confidence dey rise like bread. 🍞",
    "Two corrects! Na today you show say you no be imbecile. 😎",
    "Two straight wins! You be small god of correct. 👑",
    "Ah‑ah! 2 correct, you don wash away one village spirit. 👻❌",
    "Two corrects! Na like having cold water after work. 💦😌",
    "You don put two correct together like cement block. 🧱",
    "Two corrects! Your ancestors don send small blessing. 🙏",
    "Yes o! Two in a row, you dey represent Naija well. 🇳🇬",
    "Two straight! Your brain dey work like new engine. 🚗💨",
    "Two corrects! Na like scoring two goals for your enemy. ⚽😈",
    "You don collect two, you go soon reach five! 🔜",
    "Ah! 2 correct, your village people don keep quiet. 🤫",
    "Two corrects! You don make me smile like I just chop suya. 😋",
    "Two straight wins! Na the spark wey go start fire. 🔥",
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function onFiveStreakWin() {
  const comments = [
    "5 straight corrects! You be Odogwu wey no dey carry last! 🔥🔥🔥",
    "Omo! 5 in a row! Your brain dey overheat with knowledge. 🧠🌡️",
    "Ah! 5 corrects! You don scatter village people’s meeting completely! 🏘️💥",
    "Five corrects! Your ancestors are dancing shaku shaku for heaven! 🕺😇",
    "You don collect 5 like king wey dey take territories. 👑🏆",
    "5 straight! Your brain dey sharper than new razor blade. 🪒🧠",
    "Chai! 5 corrects, you be original Naija genius! 🇳🇬🧠",
    "You don prove that you be Omo Olowogbogboro! 🌟🔥",
    "Five corrects! Na so you dey carry the whole quiz for head. 🚶🏾‍♂️🏋🏾",
    "Yes o! 5 straight, you don silence all critics. 🤐✅",
    "5 corrects! Your sabi dey shine like diamond on top rock. 💎✨",
    "You don break the record of wrongs – now na corrects reign. 👑",
    "Ah‑ah! 5 straight, you be the real MVP of this round. 🏅🔥",
    "Five corrects! Even your village people dey clap for you now. 👏🏘️",
    "You don turn walking encyclopedia of Naija! 📚🇳🇬",
    "5 corrects! Your brain dey produce results like factory. 🏭✅",
    "You be the one wey fit pass WAEC without reading! 🎓😅",
    "Five straight! Your ancestors don remove shame from your lineage. 😇✨",
    "You don collect 5 corrects – na person wey get 7 lives. 🐱🔥",
    "Ah! 5 corrects, your brain dey on fire, no need fuel. 🔥⛽",
    "Five corrects! You don prove that you be ogbonge omo Naija. 💪",
    "You don enter the hall of fame with this 5‑streak. 🏛️✅",
    "5 corrects! Na today you show say you be chairman of correct. 👑",
    "Your sabi dey overflow like river Niger after rain. 🌊🧠",
    "Five straight! You be the one wey dey make quiz sweet. 😋",
    "Ah‑ah! 5 corrects, you don make me proud like father wey see son graduate. 👨🏽‍🎓",
    "You don collect 5 – you be original Naija champion! 🏆🇳🇬",
    "5 corrects! Your village people don turn to your fans. 🥳",
    "You be lightning that strikes correct answers only. ⚡✅",
    "Five straight! Na so you dey oppress wrong answers. 😎",
    "You don prove that your brain na Ferrari, not keke. 🏎️💨",
    "5 corrects! Your ancestors dey book party for your village. 🎉🏘️",
    "You be the real definition of ‘I too know’. 🧠🏆",
    "Five straight! You don scatter the game like Burna Boy for stage. 🎤🔥",
    "Ah! 5 corrects, you be Naija genius certificate holder. 📜🇳🇬",
    "You don show that your IQ no be small pikin. 👶🏽❌",
    "5 corrects! Your brain dey sweet like honey from farm. 🍯🧠",
    "You just dey use correct answers do jollof rice – sweet! 🍚😋",
    "Five straight! You be the one wey make wrong answers run hide. 🏃‍♀️💨",
    "5 corrects! Your sabi dey give me goosebumps. 🐔✨",
    "Ah‑ah! 5 straight, you don collect full package of sense. 🎁🧠",
    "You be the Odogwu wey no dey lose battle. ⚔️🔥",
    "Five corrects! Your brain dey work like computer wey get RAM. 💻🚀",
    "You don prove that you be number one for this quiz. 1️⃣",
    "5 corrects! Your village people don upgrade your title. 🏘️👑",
    "You be the one wey dey make me laugh with joy. 😂😇",
    "Five straight! You just dey shine like Eko Atlantic building. 🏙️✨",
    "Ah! 5 corrects, your brain dey accelerate like jet. ✈️💨",
    "5 corrects! Na you be the king of this category. 🦁",
    "You don prove that you be born with calculator brain. 🧮🧠",
    // Warri pidgin specials
    "5 corrects! Omo, you be real Warri champion! 🔥💪",
    "Five straight! You don scatter village people like flood. 🌊😂",
    "Ah‑ah! 5 corrects, your head correct die! No be small. 🤯",
    "You don collect 5, na like you win Baba Ijebu 5 numbers! 🔮💰",
    "5 corrects! Your ancestors dey throw money for you. 💸😇",
    "You be Omo Naija wey get sense pass Einstein. 🧠🇳🇬",
    "Five straight! Na so you dey chop correct like eba. 🍛✅",
    "5 corrects! Your village people don sing your praise. 🎶🏘️",
    "You don show that you be original son of the soil. 🌍🔥",
    "Ah! 5 straight, your brain dey fire like new year cracker. 🧨🧠",
    "Five corrects! Your sabi dey shine like headlight. 💡✨",
    "You be the one wey dey disgrace wrong answers today. 😂❌",
    "5 corrects! Na like you collect 5 star from hotel. ⭐⭐⭐⭐⭐",
    "You don prove that you be better pikin. 👶🏽✅",
    "Ah‑ah! 5 straight, you don make your mama proud. 👩🏽😢",
    "Five corrects! Your village people don stop their wahala. 🏘️🚫",
    "5 corrects! You be the real MVP of the day. 🏅🔥",
    "You just dey fire correct like machine gun. 🔫✅",
    "Five straight! Na so you dey take over this quiz. 👑",
    "5 corrects! Your ancestors dey dance with joy. 💃😇",
    "You be Odogwu wey no dey carry last. 🔥🔥🔥",
    "Ah! 5 corrects, your brain dey shine like star. ⭐🧠",
    "Five straight! You don win my heart totally. 💖",
    "5 corrects! You be the professor of correct answers. 🎓✅",
    "You don collect 5 – na you get the key to success. 🔑",
    "Ah‑ah! 5 straight, you don shut down village network. 📴",
    "Five corrects! Your village people don bow for you. 🙇🏽",
    "5 corrects! Na today you prove say you be real Naija. 🇳🇬🔥",
  ];
  return comments[Math.floor(Math.random() * comments.length)];
}

export function getEndOfRoundComment(score) {
  let band = [];
  if (score >= 0 && score <= 20) {
    band = [
      "Omo! This score na real village people work. 😂",
      "You don carry last! Even okada man fit pass you. 🏍️❌",
      "Chai! Your brain don go on permanent vacation. 🏖️🧠",
      "0‑20 points! You be student wey no open book at all. 📚🙅",
      "Your ancestors are ashamed, they no go answer you. 😢",
      "This one strong! You don collect lowest score for Naija history. 📉",
      "You sure say you no be amebo? Na gist you sabi. 🗣️",
      "Ah‑ah! You scatter my record like bad fuel. 🛢️💥",
      "Village people don use your head do football. ⚽🏘️",
      "You need prayer and fasting for next round. 🙏⛪",
      "Your score na ‘F9’ – you no try at all! ❌",
      "Na so you dey represent your family? Shame! 😡",
      "You be the one wey dey make quiz look hard. 😅",
      "0‑20! Your brain dey on battery saver mode. 🔋🤏",
      "You don prove that some people no just get luck. 🍀",
      "You get village juju for head, e no allow you pass. 🪄",
      "Your score dey laugh at you – e no hide am! 😂",
      "Chai! You need to go back to your village and apologize. 🏘️😢",
      "This one na real ‘I no know anything’ energy. 😞",
      "You don spoil the game for yourself, abeg restart. 🔄",
      "Ah! 0‑20, you be the grand champion of zeroes. 🏆❌",
      "Your brain don freeze like ice water. 🧊🧠",
      "Na today you show say you be Omo Oloju full. 👁️😂",
      "Village people dey celebrate your failure with drinks. 🍻🏘️",
      "You no even try small, you just gree for wrong. 😑",
      "This score make me weak! I need to rest. 😩",
      "You don carry your bad luck come spoil my day. 🍀😠",
      "0‑20? Even calculator fit do better. 🧮✅",
      "You be the one wey dey make village proud – for bad reason. 🏘️😅",
      "Your ancestors dey ask if you be their pikin. 👼🏽❓",
      "This score na sign that you need deliverance! 🕯️🔥",
      "You don collect ‘no pass’ like it’s your birthright. 👶🏽",
      "Ah‑ah! You dey make me laugh despite the poor score. 😂😢",
      "0‑20! Your village people don collect your certificate of failure. 📜",
      "You be the real definition of ‘I no try’. 😞",
      "This score dey sting like hot pepper. 🌶️😅",
      "Na so you dey disgrace your family name? 😡",
      "0‑20! You need to go and learn from your grandma. 👵🏽📚",
      "Your brain don shut down completely – off! 🔌",
      "Chai! You don prove that village people still dey active. 🏘️",
      "This score na like no food for house – empty! 🍲",
      "0‑20! You be the one wey make me weep. 😭",
      "You no even reach average, you just dey floor. 📏",
      "Ah! You need to change your strategy, this one no work. 🔄",
      "0‑20! You don make your village people laugh for you. 😂🏘️",
      "Your sabi don run comot like thief. 🏃💨",
      "This score be like water wey no get cup – useless. 💧",
      "0‑20! You don prove that some people no just get luck. 🍀",
      "You be the one wey dey give wrong answers life. 🤲",
      "0‑20! Your ancestors don block you for heaven. 🚫😇",
    ];
  } else if (score >= 21 && score <= 30) {
    band = [
      "21‑30! You dey try small, but you still dey the bottom. 😂",
      "Your ancestors dey look you with one eye. 👀😏",
      "You don move from zero, but you never reach anywhere. 🚶🏾",
      "Ah! 21‑30, you still dey carry wahala for head. 😅",
      "You be like person wey just wake from sleep. 😴🌅",
      "This score na ‘pass’ but no be ‘distinction’. 📄",
      "You dey try, but your village people still dey laugh. 😂🏘️",
      "21‑30! Your brain dey do push‑up but no stand. 🤸🏾",
      "You dey show small sense, but the rest dey hide. 🤏",
      "Na so you dey climb slow slow like snail. 🐌",
      "You don open book small, but you no read finish. 📖",
      "Your score na like half bread – better than none. 🍞",
      "21‑30! You be the one wey dey balance between pass and fail. ⚖️",
      "You dey try to fly, but your wings small. 🐥",
      "Ah! You don prove say you no be complete mumu. 😅",
      "This score dey tell you ‘you fit do better’. 📣",
      "You be student wey dey carry extra lesson. 📚🏫",
      "21‑30! Your ancestors dey clap small, then stop. 👏",
      "You dey near the door of success, but never enter. 🚪",
      "Na today you show say you get small potential. 🌱",
      "21‑30! You be like keke wey dey climb hill – e dey struggle. 🛺⛰️",
      "You don start to understand, but the road long. 🛣️",
      "Your village people don reduce their laugh volume. 📢⬇️",
      "21‑30! You dey try your best, but best never reach. 😅",
      "You be the one wey dey make me say ‘keep trying’. 💪",
      "Ah! 21‑30, you just dey wake from your sleep. 🌅",
      "Your score sweet small like half‑ripe mango. 🥭",
      "21‑30! You be the real definition of ‘work in progress’. 🚧",
      "You dey climb mountain, but you never reach middle. 🏔️",
      "This score na like having one shoe – incomplete. 👞",
      "21‑30! Your ancestors dey give you small hope. 🙏",
      "You don prove that you fit learn, just need time. ⏳",
      "Ah! 21‑30, you be the one wey dey shame village people small. 😎",
      "You dey rise like dough, but e never swell. 🍞",
      "21‑30! Your brain dey charge like battery wey get 30%. 🔋",
      "This score na the beginning of your greatness. 🌟",
      "You be the one wey dey move from failure to average. 📈",
      "21‑30! You dey try, but I still dey laugh small. 😂😊",
      "Your village people dey watch you – no disappoint them. 👀",
      "21‑30! Na so you dey take small steps. 👣",
      "You don collect points like person wey dey gather firewood. 🔥",
      "Ah! 21‑30, you be the one wey dey give me hope. 🌈",
      "This score dey show say you no be complete write‑off. 📝",
      "21‑30! You be like person wey just learn to walk. 🚶🏾👶",
      "You dey find your way, but your compass dey shake. 🧭",
      "21‑30! Your ancestors dey consider second chance for you. 🤔",
      "You don improve small from zero, keep moving. 🚴🏾",
      "Ah! 21‑30, you be the one wey dey make village people talk. 🗣️",
      "This score na like small money – e better pass nothing. 💵",
      "21‑30! You be the ‘Mr. Trying’ of today. 🏅",
    ];
  } else if (score >= 31 && score <= 50) {
    band = [
      "31‑50! You dey average, you no bad, you no good. 😅",
      "You dey represent Naija small – no too much yet. 🇳🇬",
      "Your brain dey work, but e dey sleep sometimes. 😴🧠",
      "Ah! 31‑50, you be the one wey dey middle of the road. 🛣️",
      "This score na like having garri without soup – e okay small. 🍲",
      "You dey try, but you never reach level. 📈",
      "31‑50! You be student wey dey average. 📚",
      "Your ancestors dey nod their head, but no too much. 🙆🏾",
      "You dey show sense, but you still dey miss road. 🚧",
      "Na today you prove say you no be village champion. 🏘️",
      "31‑50! You be like person wey just cross half way. 🏁",
      "This score na like ordinary water – e no sweet, e no bitter. 💧",
      "You don move pass failure, you dey for middle class. 🏘️",
      "Ah! 31‑50, you be the one wey dey give me hope. 🌈",
      "You dey climb the ladder, but you never reach top. 🪜",
      "31‑50! Your village people dey keep quiet small. 🤫",
      "You be the one wey dey keep the balance in the quiz. ⚖️",
      "This score dey tell you ‘you fit do better’. 📣",
      "31‑50! Your brain dey on medium speed. 🚴🏾",
      "You don get corrects, but wrongs still dey follow you. 🏃‍♀️",
      "Ah! 31‑50, you be the real ‘average Nigerian’. 🇳🇬",
      "You dey try to shine, but cloud still cover you. ☁️✨",
      "31‑50! Your ancestors dey clap, but dem expect more. 👏",
      "This score na like biscuit wey break – half good. 🍪",
      "You don prove that you fit survive this quiz. 🏕️",
      "Ah! 31‑50, you be the one wey dey make me smile small. 😊",
      "31‑50! You be the ‘Mr. Okay’ of today. 👍🏽",
      "You dey move steadily like tortoise. 🐢",
      "This score dey show that your brain still dey work. 🧠",
      "31‑50! You don collect moderate points – no be small. 💪",
      "Ah! 31‑50, you be the one wey dey balance wahala. 😅",
      "You be like person wey drink half bottle of water – okay. 💧",
      "31‑50! Your village people don stop their noise. 🤫",
      "This score na like having small change after spending. 💸",
      "You don build foundation, but house never complete. 🏗️",
      "Ah! 31‑50, you be the one wey dey give me happiness small. 😊",
      "31‑50! You be the real ‘try again’ champion. 🔁",
      "You dey find correct answers, but no be all. 🔍",
      "This score dey sweet like unripe orange – e get tang. 🍊",
      "Ah! 31‑50, you be the one wey dey make me proud small. 👏",
      "You don show that you get sense, even if e small. 👌",
      "31‑50! Your ancestors dey pray for improvement. 🙏",
      "This score na like okada wey get half tank. ⛽🏍️",
      "You be the ‘Gradual Graduate’ of this quiz. 🎓",
      "Ah! 31‑50, you don cross the line of shame. ✅",
      "31‑50! You be the one wey dey move from zero to hero small. 🦸🏾",
      "You dey try your best, but your best never reach maximum. 💯",
      "This score dey tell me say you go sabi soon. ⏳",
      "31‑50! Your village people don begin to reason. 🤔",
      "Ah! 31‑50, you be the one wey dey make the game interesting. 🎯",
    ];
  } else if (score >= 51 && score <= 80) {
    band = [
      "51‑80! You don enter ‘sharp guy’ zone! 🔥🧠",
      "Omo! This score dey sweet like chilled zobo! 🍹😋",
      "You don pass average, you dey shine! ✨",
      "51‑80! Your ancestors dey proud well well! 🎉😇",
      "You be Naija genius in the making! 🧠🇳🇬",
      "Ah! 51‑80, your brain dey fire on all cylinders. 🔥🔥",
      "This score na like having complete amala with gbegiri. 🍲✅",
      "You dey represent Naija with small pride. 💪",
      "51‑80! Your village people don turn to your small fans. 🥳",
      "You be the one wey dey climb success mountain. 🏔️",
      "This score dey show that you sabi book well. 📚🧠",
      "Ah! 51‑80, you be sharp guy, no be knife! 🔪😎",
      "You don collect good points, e dey make me happy. 😊",
      "51‑80! You be the student wey dey pass exam. 🎓",
      "Your brain dey work like well‑oiled machine. ⚙️🧠",
      "This score na like jollof rice wey get chicken. 🍗🍚",
      "Ah! 51‑80, you don join the league of sensible people. 🏅",
      "You be the one wey dey give me confidence for Naija. 🇳🇬",
      "51‑80! Your ancestors dey celebrate you for real. 🕺",
      "You dey try reach 100, you no far. 🎯",
      "This score dey sweet like suya with plenty pepper. 🍢🌶️",
      "51‑80! You be the real definition of ‘I sabi’. 🤓",
      "Ah! 51‑80, you don reduce village people’s power. ⚡",
      "Your brain dey produce correct answers like factory. 🏭✅",
      "51‑80! You be the one wey dey make this game fun. 🎮",
      "This score na like having full tank of petrol. ⛽",
      "You don prove that you be better pikin. 👶🏽🔥",
      "51‑80! Your ancestors dey send you blessings. 🙏✨",
      "Ah! 51‑80, you be the ‘Star of the Day’. ⭐",
      "You be the one wey dey carry Naija for head. 🇳🇬🏆",
      "This score dey tell me say you go reach 100 soon. 💯",
      "51‑80! You be the one wey dey make me proud. 👏😊",
      "Your sabi dey shine like streetlight at night. 💡✨",
      "Ah! 51‑80, you don enter correct‑answer party. 🎉",
      "You be the one wey dey disgrace wrong answers. 😂",
      "This score na like having money for pocket after market. 💰",
      "51‑80! Your village people don begin to respect you. 🏘️👏",
      "You dey climb the ladder of wisdom fast. 🪜💨",
      "Ah! 51‑80, you don prove that you be Omo Naija correct. 🇳🇬",
      "This score dey sweet like cold water after work. 💦😌",
      "51‑80! You be the one wey dey carry the game. 🏋🏾",
      "Your brain dey click like camera shutter. 📸🧠",
      "Ah! 51‑80, you be the real MVP of the middle. 🏅",
      "You don prove that you no be small pikin. 👶🏽❌",
      "This score na like winning small money – joy. 💵😊",
      "51‑80! Your ancestors dey say ‘this one go make us proud’. 🗣️",
      "You be the ‘Pace Setter’ for this round. 🏃🏾",
      "Ah! 51‑80, you don scatter village people’s doubt. 🤷",
      "51‑80! You be the one wey dey light up the quiz. 💡",
      "This score dey show that you fit do great things. 🌟",
    ];
  } else if (score >= 81 && score <= 100) {
    band = [
      "81‑100! Omo, you be Odogwu! 🔥🔥🔥",
      "You don carry ‘A’ plus plus! Your ancestors dey dance! 💃😇",
      "Ah! This score sweet pass honey from the rock. 🍯✨",
      "You be original Naija genius – no be copy! 🇳🇬🧠",
      "81‑100! Your brain dey on fire, no need fuel. 🔥⛽",
      "You don prove that you be professor of correct answers. 🎓✅",
      "This score na like having jollof rice with full chicken. 🍗🍚",
      "81‑100! Your village people don crown you king. 👑🏘️",
      "You be the one wey dey make me shout ‘Naija no dey carry last!’ 🇳🇬🏆",
      "Ah! 81‑100, your sabi dey shine like full moon. 🌕✨",
      "You don enter Hall of Fame for NaijaGenius. 🏛️🔥",
      "This score na like winning lottery for your village. 💰🎉",
      "81‑100! You be the real definition of ‘I too know’. 🤓",
      "Your ancestors dey arrange praise party for you. 🎉😇",
      "Ah! 81‑100, you don silence all the doubters. 🤐✅",
      "You be the one wey dey make quiz look easy. 😎",
      "This score dey sweet like suya from Glover Court. 🍢😋",
      "81‑100! You be the ‘Brain Master’ of the day. 🧠👑",
      "You don prove that your village no get power over you. 🏘️❌",
      "Ah! 81‑100, you be the real Star Boy! 🌟🇳🇬",
      "This score na like having air‑conditioner during heat. ❄️😌",
      "81‑100! Your brain dey sharper than double‑edge sword. ⚔️🧠",
      "You be the one wey dey carry Nigeria to the top. 🇳🇬🔝",
      "Ah! 81‑100, you don make your family proud! 👨‍👩‍👧‍👦🎉",
      "This score dey make me emotional – you try! 😢👏",
      "81‑100! You be the ‘Quiz Conqueror’. ⚔️✅",
      "Your sabi dey overflow like River Niger. 🌊🧠",
      "Ah! 81‑100, you don collect almost perfect score! 💯",
      "You be the one wey dey show that Naija sabi. 🇳🇬🔥",
      "This score na like getting promotion for work. 👔🎉",
      "81‑100! You be the real Oga for the quiz. 👨🏽‍💼",
      "Ah! 81‑100, your ancestors dey shed tears of joy. 😭😇",
      "You don prove that hard work dey pay. 💪💵",
      "This score dey sweet like Egusi soup with fresh fish. 🍲😋",
      "81‑100! You be the one wey dey set standard. 📏✅",
      "Ah! 81‑100, you don put village people to shame. 😂🏘️",
      "You be the ‘Genius of the Week’. 🏆🧠",
      "This score na like riding bicycle downhill – smooth! 🚴🏾💨",
      "81‑100! You don enter the league of extraordinary Nigerians. 🇳🇬🌟",
      "Ah! 81‑100, your brain dey work like supercomputer. 💻🧠",
      "You be the one wey dey make this game sweet. 😋",
      "This score dey shine like diamond from Kono. 💎✨",
      "81‑100! You don make me believe in Naija again. 🇳🇬😊",
      "Ah! 81‑100, you be the real ‘Omo Ologun’. 💪",
      "You don prove that you be above average. 📈✅",
      "This score na like getting all answers for exam. 📝😅",
      "81‑100! You be the one wey dey represent the best. 🏅",
      "Ah! 81‑100, your ancestors dey call you ‘Our Pride’. 🗣️🏘️",
      "You be the ‘Champion of Correct’ for today. 🏆",
      "This score dey make me want to dance shaku shaku. 🕺🎶",
    ];
  } else if (score >= 101 && score <= 110) {
    band = [
      "101‑110! Omo! You be Odogwu wey no dey carry last! 🔥🔥🔥",
      "You don collect pass 100! Your ancestors dey do gymnastic! 🤸🏾😇",
      "Ah! 101‑110, you be Naija Einstein! 🇳🇬🧠",
      "This score na like jollof rice wey dey cater for whole party. 🍚🎉",
      "101‑110! Your brain dey produce pure gold! 🥇🧠",
      "You don prove that you be the real ‘I know it all’. 🤓",
      "Ah! 101‑110, you be the one wey dey make me stand up and clap. 👏😭",
      "You be ‘Genius Extraordinaire’! 🌟🔥",
      "This score dey sweet like ogogoro wey correct. 🍶😋",
      "101‑110! Your village people don bow down. 🙇🏾🏘️",
      "You be the one wey dey carry Nigeria like shoulder pad. 🇳🇬💪",
      "Ah! 101‑110, you don shame failure forever. 🚫❌",
      "This score na like winning Champions League. ⚽🏆",
      "101‑110! You be the real MVP of the century! 🏅",
      "Your brain dey on another level, no be here. 🚀🧠",
      "Ah! 101‑110, you don enter the zone of the champions. 🏆✨",
      "You be the one wey dey make me proud to be Naija. 🇳🇬😊",
      "This score dey sweet like kilishi wey fresh. 🍖😋",
      "101‑110! Your ancestors dey open champagne for heaven. 🍾😇",
      "You be the ‘Grand Master of Answers’. ♟️👑",
      "Ah! 101‑110, you don prove that your brain na Ferrari. 🏎️💨",
      "You be the one wey dey set record wey dem go talk. 🗣️📈",
      "This score dey make me want to give you award. 🏆📜",
      "101‑110! You be the real ‘King of Knowledge’. 👑🧠",
      "Ah! 101‑110, your village people don send you gift. 🎁🏘️",
      "You be the one wey dey make quiz look like child’s play. 👶🏽🎮",
      "This score na like climbing mount Everest of wisdom. 🏔️🧠",
      "101‑110! You don enter the book of ‘Ogbonge Nigerians’. 📕🇳🇬",
      "You be the one wey dey make me speechless. 😮🔥",
      "Ah! 101‑110, you don prove that impossible no dey. 🚫✅",
      "This score dey shine like the sun for afternoon. ☀️✨",
      "101‑110! You be the real ‘Professor of Correct’. 🎓🔝",
      "You be the one wey dey carry the whole quiz for back. 🎒💪",
      "Ah! 101‑110, your sabi dey intimidate wrong answers. 👻❌",
      "This score dey sweet like zobo wey cold well. 🍹😋",
      "101‑110! You be the ‘Pillar of Naija Wisdom’. 🏛️🇳🇬",
      "You don prove that your brain get extra capacity. 🧠➕",
      "Ah! 101‑110, you be the one wey dey make history today. 📖✨",
      "This score na like having all the answers before the question. 🔮",
      "101‑110! You be the one wey dey make me scream with joy. 🗣️😄",
      "You be the real ‘Quiz Tyrant’ – no correct escapes you. 👑",
      "Ah! 101‑110, you don collect the crown. 🤴🏾✅",
      "This score dey show that you be original Naija ambassador. 🇳🇬🌍",
      "101‑110! You be the one wey dey bring glory to your village. 🏘️✨",
      "You don prove that with focus, anything fit happen. 💯",
      "Ah! 101‑110, you be the ‘Oracle of Correct Answers’. 🕯️🧠",
      "This score dey make me want to compose song for you. 🎵😅",
      "101‑110! You be the real ‘Omo Olowogbogboro’. 🌟🔥",
    ];
  } else if (score >= 111 && score <= 120) {
    band = [
      "111‑120! Omo! You be the God of this quiz! 🔥🔥🔥",
      "Perfect score! Your ancestors don take over your brain! 😇🧠",
      "Ah! 111‑120, you be Naija’s finest! 🇳🇬👑",
      "This score na like winning World Cup. 🏆⚽",
      "111‑120! Your brain dey on autopilot of correctness. 🚀✅",
      "You don prove that you be the real ‘I know everything’. 🤯",
      "Ah! 111‑120, you be the one wey dey make me cry tears of joy. 😭❤️",
      "This score dey sweet like fresh bread with sardine. 🍞🐟",
      "111‑120! Your village people don declare public holiday. 🏘️🎉",
      "You be the ‘Ultimate Genius of Nigeria’. 🧠🌟",
      "Ah! 111‑120, you don reach the highest level! 🏔️✅",
      "This score na like having all the wealth of Africa. 💰🌍",
      "111‑120! You be the real definition of ‘perfection’. 💯",
      "Your ancestors dey carry you on their shoulders. 👏😇",
      "Ah! 111‑120, you don shut down the quiz! 🖥️❌",
      "You be the one wey dey make me say ‘Naija no dey carry last’! 🏆🇳🇬",
      "This score dey shine like full diamond. 💎✨",
      "111‑120! You be the ‘Chairman of Correct Answers’. 🪑👑",
      "Ah! 111‑120, you don prove that you be the best. 1️⃣",
      "You be the one wey dey make history for this game. 📖🔥",
      "This score na like getting all questions right for JAMB. 🎓📝",
      "111‑120! You be the real ‘Quiz Messiah’. ✨🙌",
      "Ah! 111‑120, your brain dey operate at 1000% capacity. 🧠⚡",
      "This score dey make me want to bow for you. 🙇🏾😅",
      "111‑120! You be the one wey dey represent heaven. 😇🏆",
      "You don prove that your village no fit hold you back. 🏘️🚫",
      "Ah! 111‑120, you be the ‘Champion of Champions’. 🏅🏅",
      "This score dey sweet like fresh palm wine. 🍷😋",
      "111‑120! You be the one wey dey give Naija hope. 🇳🇬🌈",
      "You be the real ‘Ogbonge Omo Naija’. 🔥💪",
      "Ah! 111‑120, you don collect all the accolades. 🎖️✅",
      "This score na like finding gold under your bed. 🥇🛏️",
      "111‑120! Your village people don name street after you. 🏘️🛣️",
      "You be the one wey dey make the game look simple. 😎",
      "Ah! 111‑120, you be the ‘King of Knowledge’. 👑🧠",
      "This score dey show that you be original brain master. 🤯",
      "111‑120! You don enter the Guinness Book of Corrects. 📕✅",
      "You be the one wey dey carry light for our path. 💡🔥",
      "Ah! 111‑120, your ancestors dey sing ‘You are worthy’. 🎵😇",
      "This score dey sweet like hearing ‘you don win jackpot’. 💰🔊",
      "111‑120! You be the real ‘Super Brain’. 🦸🏾🧠",
      "You don prove that impossible na nothing for you. 🚫✅",
      "Ah! 111‑120, you be the ‘Legend of this platform’. 📱🏆",
      "This score na like finishing race with world record. 🏃🏾⏱️",
      "111‑120! You be the one wey dey make us proud. 👏🇳🇬",
    ];
  }
  return band[Math.floor(Math.random() * band.length)];
}