const nigeriaHistory = [
{question:"In what year did Nigeria officially become a nation?",optionA:"1914",optionB:"1960",optionC:"1963",optionD:"1999",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Nigeria gained independence in which year?",optionA:"1960",optionB:"1963",optionC:"1958",optionD:"1970",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Who coined the name Nigeria?",optionA:"Flora Shaw",optionB:"Lord Lugard",optionC:"Mungo Park",optionD:"Mary Slessor",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Nigeria became a republic in what year?",optionA:"1963",optionB:"1960",optionC:"1970",optionD:"1979",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the first Nigerian President?",optionA:"Nnamdi Azikiwe",optionB:"Tafawa Balewa",optionC:"Aguiyi Ironsi",optionD:"Yakubu Gowon",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"The Nigerian Civil War began in what year?",optionA:"1967",optionB:"1960",optionC:"1970",optionD:"1975",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"How many states does Nigeria currently have?",optionA:"36",optionB:"30",optionC:"33",optionD:"40",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"What is Nigeria's current capital city?",optionA:"Abuja",optionB:"Lagos",optionC:"Kano",optionD:"Ibadan",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Who was Nigeria's first military head of state?",optionA:"Aguiyi Ironsi",optionB:"Yakubu Gowon",optionC:"Ibrahim Babangida",optionD:"Muhammadu Buhari",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Which year was the current constitution adopted?",optionA:"1999",optionB:"1979",optionC:"1963",optionD:"1960",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"The 1914 amalgamation joined which two protectorates?",optionA:"North and South",optionB:"East and West",optionC:"Lagos and Kano",optionD:"Borno and Oyo",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Who was the first Prime Minister?",optionA:"Tafawa Balewa",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Obafemi Awolowo",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"What year did the civil war end?",optionA:"1970",optionB:"1967",optionC:"1973",optionD:"1969",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the military leader during the war?",optionA:"Yakubu Gowon",optionB:"Aguiyi Ironsi",optionC:"Olusegun Obasanjo",optionD:"Murtala Mohammed",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Which river runs through Nigeria's capital?",optionA:"Niger",optionB:"Benue",optionC:"Ogun",optionD:"Cross River",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What is the Nigerian currency called?",optionA:"Naira",optionB:"Dollar",optionC:"Cedi",optionD:"Riyal",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"What does the white color represent?",optionA:"Peace",optionB:"Energy",optionC:"Agriculture",optionD:"Strength",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Which colonial administrator led the amalgamation?",optionA:"Lord Lugard",optionB:"Sir Robertson",optionC:"Mungo Park",optionD:"Flora Shaw",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"The national assembly has how many senators?",optionA:"109",optionB:"360",optionC:"100",optionD:"50",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who wrote the novel Things Fall Apart?",optionA:"Chinua Achebe",optionB:"Wole Soyinka",optionC:"Flora Nwapa",optionD:"Ken Saro-Wiwa",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Which city is known as Center of Excellence?",optionA:"Lagos",optionB:"Abuja",optionC:"Kano",optionD:"Port Harcourt",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"When was the first democratic transition?",optionA:"1979",optionB:"1960",optionC:"1999",optionD:"2007",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Which region sought secession in 1967?",optionA:"Eastern Region",optionB:"Western Region",optionC:"Northern Region",optionD:"Midwest",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Who is the author of Things Fall Apart?",optionA:"Chinua Achebe",optionB:"Wole Soyinka",optionC:"Buchi Emecheta",optionD:"Ken Saro-Wiwa",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"What is the national football team name?",optionA:"Super Eagles",optionB:"Green Eagles",optionC:"Super Falcons",optionD:"Lions",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which event happened in October 1960?",optionA:"Independence",optionB:"Republic",optionC:"Civil War",optionD:"Amalgamation",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Who was the president in 1999?",optionA:"Olusegun Obasanjo",optionB:"Goodluck Jonathan",optionC:"Umaru YarAdua",optionD:"Buhari",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"What does the green color symbolize?",optionA:"Agriculture",optionB:"Peace",optionC:"Unity",optionD:"Wealth",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Nigeria joined OPEC in what year?",optionA:"1971",optionB:"1960",optionC:"1980",optionD:"1990",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Which hero is on the 20 Naira?",optionA:"Murtala Mohammed",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Who was Nigeria's leader in 2023?",optionA:"Bola Tinubu",optionB:"Buhari",optionC:"Obasanjo",optionD:"Jonathan",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"When did Nigeria adopt the Naira?",optionA:"1973",optionB:"1960",optionC:"1999",optionD:"1980",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which city was the former capital?",optionA:"Lagos",optionB:"Abuja",optionC:"Kaduna",optionD:"Enugu",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"What is the official state language?",optionA:"English",optionB:"Hausa",optionC:"Igbo",optionD:"Yoruba",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Which major industry drives the economy?",optionA:"Petroleum",optionB:"Tourism",optionC:"Fishing",optionD:"Mining",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Who was the president from 2015-2023?",optionA:"Muhammadu Buhari",optionB:"Obasanjo",optionC:"Jonathan",optionD:"YarAdua",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"The first oil discovery occurred where?",optionA:"Oloibiri",optionB:"Lagos",optionC:"Kano",optionD:"Enugu",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 1970s economic boom called?",optionA:"Oil Boom",optionB:"Gold Rush",optionC:"Green Age",optionD:"Industrial Age",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which body conducts national elections?",optionA:"INEC",optionB:"EFCC",optionC:"Police",optionD:"Court",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"What does BVAS stand for?",optionA:"Voter Accreditation",optionB:"Voter System",optionC:"Voter Count",optionD:"Voter Check",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Which president ended fuel subsidies 2023?",optionA:"Bola Tinubu",optionB:"Buhari",optionC:"Jonathan",optionD:"Obasanjo",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"When was the eNaira launched?",optionA:"2021",optionB:"2020",optionC:"2022",optionD:"2023",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Who was the first female NAFDAC head?",optionA:"Dora Akunyili",optionB:"Grace Alele",optionC:"Funmilayo Kuti",optionD:"Okongwu",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What is the national motto?",optionA:"Unity and Faith",optionB:"Peace and Love",optionC:"Growth and Power",optionD:"God Bless Nigeria",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Which city hosted 1973 All-Africa Games?",optionA:"Lagos",optionB:"Abuja",optionC:"Kano",optionD:"Enugu",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"When did the Fourth Republic start?",optionA:"1999",optionB:"1995",optionC:"2000",optionD:"1990",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Which landmark court handles regional cases?",optionA:"ECOWAS Court",optionB:"Supreme Court",optionC:"High Court",optionD:"Sharia Court",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"What is the name of the Senate?",optionA:"National Assembly",optionB:"Senate House",optionC:"Assembly of Reps",optionD:"Council",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"How many senatorial districts per state?",optionA:"Three",optionB:"Two",optionC:"Four",optionD:"Five",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"What is the largest movie industry?",optionA:"Nollywood",optionB:"Hollywood",optionC:"Bollywood",optionD:"Tollywood",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Which year did Nigeria gain formal independence?",optionA:"1960",optionB:"1963",optionC:"1970",optionD:"1999",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"What is Nigeria's official national currency?",optionA:"Naira",optionB:"Dollar",optionC:"Cedi",optionD:"Pound",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Who is the current Nigerian President in 2026?",optionA:"Bola Tinubu",optionB:"Obasanjo",optionC:"Buhari",optionD:"Atiku",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Which city is the administrative capital of Nigeria?",optionA:"Abuja",optionB:"Lagos",optionC:"Kano",optionD:"Ibadan",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"The 1914 amalgamation joined which two protectorates?",optionA:"North and South",optionB:"East and West",optionC:"Lagos and Kano",optionD:"Borno and Oyo",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Which major religion is prevalent in the North?",optionA:"Islam",optionB:"Christianity",optionC:"Buddhism",optionD:"Hinduism",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What does the green color on flag represent?",optionA:"Agriculture",optionB:"Peace",optionC:"Unity",optionD:"Wealth",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"When did Nigeria become a republic?",optionA:"1963",optionB:"1960",optionC:"1970",optionD:"1979",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who led the 1966 military coup?",optionA:"Chukwuma Kaduna Nzeogwu",optionB:"Aguiyi Ironsi",optionC:"Yakubu Gowon",optionD:"Murtala Mohammed",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What is the largest ethnic group in Nigeria?",optionA:"Hausa-Fulani",optionB:"Yoruba",optionC:"Igbo",optionD:"Ijaw",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Which state is known as the Coal City?",optionA:"Enugu",optionB:"Kano",optionC:"Lagos",optionD:"Abuja",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the first female NAFDAC director?",optionA:"Dora Akunyili",optionB:"Grace Alele",optionC:"Funmilayo Kuti",optionD:"Okonjo-Iweala",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Nigeria's national anthem was adopted in what year?",optionA:"1978",optionB:"1960",optionC:"1963",optionD:"1999",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"The Nigerian Civil War ended in what year?",optionA:"1970",optionB:"1967",optionC:"1973",optionD:"1969",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the military leader during the war?",optionA:"Yakubu Gowon",optionB:"Aguiyi Ironsi",optionC:"Olusegun Obasanjo",optionD:"Murtala Mohammed",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What is the name of Nigeria's legislative body?",optionA:"National Assembly",optionB:"Senate House",optionC:"Assembly of Reps",optionD:"Council",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Nigeria joined the OPEC in what year?",optionA:"1971",optionB:"1960",optionC:"1980",optionD:"1990",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Who is the author of Things Fall Apart?",optionA:"Chinua Achebe",optionB:"Wole Soyinka",optionC:"Flora Nwapa",optionD:"Ken Saro-Wiwa",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"What does the white color represent?",optionA:"Peace",optionB:"Energy",optionC:"Strength",optionD:"Unity",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Which city is the former capital of Nigeria?",optionA:"Lagos",optionB:"Abuja",optionC:"Kaduna",optionD:"Enugu",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"How many senatorial districts per state?",optionA:"Three",optionB:"Two",optionC:"Four",optionD:"Five",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Who was the first Nigerian military leader?",optionA:"Aguiyi Ironsi",optionB:"Yakubu Gowon",optionC:"Ibrahim Babangida",optionD:"Muhammadu Buhari",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What is Nigeria's largest movie industry?",optionA:"Nollywood",optionB:"Hollywood",optionC:"Bollywood",optionD:"Tollywood",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"The 2023 election winner was which candidate?",optionA:"Bola Tinubu",optionB:"Atiku Abubakar",optionC:"Peter Obi",optionD:"Rabiu Kwankwaso",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Which hero appears on the 20 Naira note?",optionA:"Murtala Mohammed",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Which region sought secession in 1967?",optionA:"Eastern Region",optionB:"Western Region",optionC:"Northern Region",optionD:"Midwest",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the national football team name?",optionA:"Super Eagles",optionB:"Green Eagles",optionC:"Super Falcons",optionD:"Lions",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which year marked the current democracy?",optionA:"1999",optionB:"1960",optionC:"1963",optionD:"2007",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the official language of Nigeria?",optionA:"English",optionB:"Hausa",optionC:"Igbo",optionD:"Yoruba",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which industry dominates the Nigerian economy?",optionA:"Petroleum",optionB:"Tourism",optionC:"Fishing",optionD:"Mining",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"What does BVAS stand for?",optionA:"Voter Accreditation",optionB:"Voter System",optionC:"Voter Count",optionD:"Voter Check",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Which body conducts national elections?",optionA:"INEC",optionB:"EFCC",optionC:"Police",optionD:"Court",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Where was the first oil discovered?",optionA:"Oloibiri",optionB:"Lagos",optionC:"Kano",optionD:"Enugu",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 1970s economic period called?",optionA:"Oil Boom",optionB:"Gold Rush",optionC:"Green Age",optionD:"Industrial Age",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Who was president from 2015 to 2023?",optionA:"Muhammadu Buhari",optionB:"Obasanjo",optionC:"Jonathan",optionD:"YarAdua",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which state is called Center of Excellence?",optionA:"Lagos",optionB:"Abuja",optionC:"Kano",optionD:"Port Harcourt",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"When was the eNaira launched?",optionA:"2021",optionB:"2020",optionC:"2022",optionD:"2023",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"What is the national motto of Nigeria?",optionA:"Unity and Faith",optionB:"Peace and Love",optionC:"Growth and Power",optionD:"God Bless Nigeria",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which city hosted the 1973 All-Africa Games?",optionA:"Lagos",optionB:"Abuja",optionC:"Kano",optionD:"Enugu",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Which year did the Fourth Republic start?",optionA:"1999",optionB:"1995",optionC:"2000",optionD:"1990",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which court handles regional legal cases?",optionA:"ECOWAS Court",optionB:"Supreme Court",optionC:"High Court",optionD:"Sharia Court",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Who was the first Prime Minister?",optionA:"Tafawa Balewa",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Which colonial leader pushed the amalgamation?",optionA:"Lord Lugard",optionB:"Sir Robertson",optionC:"Mungo Park",optionD:"Flora Shaw",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What does the red color represent?",optionA:"Strength",optionB:"Peace",optionC:"Energy",optionD:"Agriculture",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which region is historically Northern Nigeria?",optionA:"The North",optionB:"The South",optionC:"The West",optionD:"The East",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Who was the president in 1999?",optionA:"Olusegun Obasanjo",optionB:"Goodluck Jonathan",optionC:"Umaru YarAdua",optionD:"Buhari",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"When did Nigeria adopt the Naira?",optionA:"1973",optionB:"1960",optionC:"1999",optionD:"1980",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which hero appears on the 50 Naira?",optionA:"Unity Statue",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What is the name of the legislative chamber?",optionA:"National Assembly",optionB:"Senate House",optionC:"Assembly of Reps",optionD:"Council",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which president ended fuel subsidies 2023?",optionA:"Bola Tinubu",optionB:"Buhari",optionC:"Jonathan",optionD:"Obasanjo",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which year was the N-Power program launched?",optionA:"2016",optionB:"2015",optionC:"2017",optionD:"2018",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the first Chibok girl rescued?",optionA:"Amina Ali",optionB:"Sarah Amos",optionC:"Deborah Samuel",optionD:"Grace John",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What is the full name of NEDC?",optionA:"North East Commission",optionB:"North East Development",optionC:"North East Council",optionD:"North East Group",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"The ERGP stands for what plan?",optionA:"Economic Recovery Plan",optionB:"Economic Growth Plan",optionC:"Economic Reform Plan",optionD:"Economic Resource Plan",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Which former VP passed in 2017?",optionA:"Alex Ekwueme",optionB:"Atiku Abubakar",optionC:"Goodluck Jonathan",optionD:"Namadi Sambo",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"June 12 is now known as?",optionA:"Democracy Day",optionB:"Unity Day",optionC:"Freedom Day",optionD:"Republic Day",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"The AfCFTA agreement was signed when?",optionA:"2018",optionB:"2017",optionC:"2019",optionD:"2020",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Which militant group emerged in 2016?",optionA:"Avengers",optionB:"Delta Force",optionC:"Niger Group",optionD:"Sea Warriors",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What railway line was tested in 2019?",optionA:"Lagos-Ibadan",optionB:"Abuja-Kaduna",optionC:"Kano-Lagos",optionD:"Port-Enugu",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was re-elected AfDB President 2019?",optionA:"Akinwumi Adesina",optionB:"Ngozi Okonjo",optionC:"Babatunde Fashola",optionD:"Yemi Osinbajo",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"When was the first COVID case?",optionA:"2020",optionB:"2019",optionC:"2021",optionD:"2018",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Which protest movement rose in 2020?",optionA:"EndSARS",optionB:"EndPolice",optionC:"EndCorruption",optionD:"EndHunger",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"The PIA was passed in what year?",optionA:"2021",optionB:"2020",optionC:"2019",optionD:"2022",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the Chief of Army Staff?",optionA:"Ibrahim Attahiru",optionB:"Tukur Buratai",optionC:"Farouk Yahaya",optionD:"Taoreed Lagbaja",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What happened in October 2020?",optionA:"EndSARS protests",optionB:"Election",optionC:"Budget pass",optionD:"Flood",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Which platform was banned in 2021?",optionA:"Twitter",optionB:"Facebook",optionC:"WhatsApp",optionD:"Telegram",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 2022 climate event?",optionA:"Flood disaster",optionB:"Drought",optionC:"Heatwave",optionD:"Storm",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"The Electoral Act was amended when?",optionA:"2022",optionB:"2021",optionC:"2020",optionD:"2023",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What is the IReV portal for?",optionA:"Result Viewing",optionB:"Voter Check",optionC:"Result Count",optionD:"Data Entry",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"What was the 2023 naira policy?",optionA:"Redesign",optionB:"Devaluation",optionC:"Revaluation",optionD:"Scrapping",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What was removed in May 2023?",optionA:"Fuel subsidy",optionB:"Tax",optionC:"Debt",optionD:"Grant",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"The CBN governor was suspended when?",optionA:"2023",optionB:"2022",optionC:"2024",optionD:"2021",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What ministry was created in 2023?",optionA:"Marine Economy",optionB:"Blue Economy",optionC:"Sea Economy",optionD:"Ocean Economy",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"What law funds indigent students?",optionA:"Student Loan Act",optionB:"Education Act",optionC:"Tuition Act",optionD:"Grant Act",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What is the CNG initiative?",optionA:"Gas for cars",optionB:"Solar power",optionC:"Wind power",optionD:"Oil power",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who affirmed the 2023 election?",optionA:"Supreme Court",optionB:"High Court",optionC:"Appeal Court",optionD:"Election Tribunal",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Which highway began in 2024?",optionA:"Coastal Highway",optionB:"Expressway",optionC:"Rail line",optionD:"Airway",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What caused 2024 exchange rate issues?",optionA:"Naira volatility",optionB:"Oil price",optionC:"Gold price",optionD:"Tax rate",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What was digitized in 2025?",optionA:"Procurement",optionB:"Education",optionC:"Health",optionD:"Police",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What sector grew in 2025?",optionA:"Agriculture",optionB:"Oil",optionC:"Service",optionD:"Tourism",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2026 process called?",optionA:"Constitutional Review",optionB:"Policy Review",optionC:"Tax Review",optionD:"Law Review",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What was re-initiated in 2026?",optionA:"National Census",optionB:"Voter Reg",optionC:"Tax Reg",optionD:"Debt Reg",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Which project opened in 2026?",optionA:"Coastal Highway",optionB:"Port",optionC:"Airport",optionD:"Bridge",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What characterizes Nigeria's mid-2026?",optionA:"Structural reform",optionB:"Oil boom",optionC:"Peace",optionD:"Unity",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Who is the current AfDB president?",optionA:"Akinwumi Adesina",optionB:"Ngozi Okonjo",optionC:"Babatunde Fashola",optionD:"Yemi Osinbajo",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"What was the 1933 act?",optionA:"Protectorate Court",optionB:"High Court",optionC:"Magistrate Court",optionD:"Supreme Court",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What favored large foreign firms?",optionA:"Monopoly",optionB:"Free trade",optionC:"Small business",optionD:"Fair trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which ruling checked military power?",optionA:"Lakanmi",optionB:"Ondo",optionC:"Lagos",optionD:"Gani",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What did the 1975 decree create?",optionA:"Revenue Court",optionB:"Supreme Court",optionC:"High Court",optionD:"Appeal Court",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What replaced the Privy Council?",optionA:"Supreme Court",optionB:"High Court",optionC:"Appeal Court",optionD:"Sharia Court",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What defined the Second Republic?",optionA:"Presidentialism",optionB:"Parliamentary",optionC:"Monarchy",optionD:"Military",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Who ruled on the corruption act?",optionA:"Supreme Court",optionB:"High Court",optionC:"Appeal Court",optionD:"Sharia Court",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Which state lost inland waterways?",optionA:"Lagos",optionB:"Ondo",optionC:"Ogun",optionD:"Kano",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What caused 1980s hardship?",optionA:"Structural Adjustment",optionB:"Oil boom",optionC:"Green age",optionD:"Industrial age",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What reinforced corporate accountability?",optionA:"Gani Fawehinmi",optionB:"Ondo",optionC:"Lagos",optionD:"Supreme",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Who owns the mandate?",optionA:"Political Party",optionB:"Candidate",optionC:"Voter",optionD:"INEC",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What was the bad bank?",optionA:"AMCON",optionB:"CBN",optionC:"Naira",optionD:"Bank",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the new petroleum law?",optionA:"PIA",optionB:"Oil Act",optionC:"Gas Act",optionD:"Petroleum Act",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 2012 protest?",optionA:"Occupy Nigeria",optionB:"EndSARS",optionC:"Election",optionD:"Food",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 1978 land act?",optionA:"Land Use Act",optionB:"Property Act",optionC:"Rent Act",optionD:"Housing Act",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Who led the 1967 secessionist movement?",optionA:"Odumegwu Ojukwu",optionB:"Yakubu Gowon",optionC:"Aguiyi Ironsi",optionD:"Murtala Mohammed",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"The 1963 constitution declared Nigeria a?",optionA:"Republic",optionB:"Monarchy",optionC:"Dominion",optionD:"Colony",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 1979 constitution transition?",optionA:"Democracy",optionB:"Military rule",optionC:"Dictatorship",optionD:"Monarchy",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the military head in 1983?",optionA:"Muhammadu Buhari",optionB:"Babangida",optionC:"Abacha",optionD:"Obasanjo",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"When was the 4th Republic established?",optionA:"1999",optionB:"1995",optionC:"1990",optionD:"2003",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 1912 indirect rule?",optionA:"Lugard Policy",optionB:"British Law",optionC:"Native Law",optionD:"Colonial Act",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What was the 1929 revolt?",optionA:"Women's War",optionB:"Tax Riot",optionC:"Trade War",optionD:"Civil War",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 1944 NCNC founder?",optionA:"Nnamdi Azikiwe",optionB:"Awolowo",optionC:"Bello",optionD:"Balewa",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What occurred on Oct 1 1960?",optionA:"Independence",optionB:"Republic",optionC:"Civil War",optionD:"Amalgamation",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Which region had the 1962 crisis?",optionA:"Western Region",optionB:"Eastern Region",optionC:"Northern Region",optionD:"Midwest",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 1963 mid-west formation?",optionA:"Regional change",optionB:"State creation",optionC:"Election",optionD:"Coup",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"What did the 1975 decree create?",optionA:"Revenue Court",optionB:"Supreme Court",optionC:"High Court",optionD:"Appeal Court",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Which year did Nigeria join OPEC?",optionA:"1971",optionB:"1960",optionC:"1980",optionD:"1990",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Who was prime minister at independence?",optionA:"Tafawa Balewa",optionB:"Nnamdi Azikiwe",optionC:"Bello",optionD:"Awolowo",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"The 1966 coup led to what?",optionA:"Military rule",optionB:"Republic",optionC:"Democracy",optionD:"Monarchy",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What does the 1967 conflict represent?",optionA:"Civil War",optionB:"Tax War",optionC:"Trade War",optionD:"Border War",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"The 1976 court created was?",optionA:"Court of Appeal",optionB:"Supreme Court",optionC:"High Court",optionD:"Sharia Court",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2002 Ondo case?",optionA:"Corruption Act",optionB:"Tax Act",optionC:"Election Act",optionD:"Land Act",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"What does the 2004 Lagos case?",optionA:"Inland Waterways",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Who signed the 1999 constitution?",optionA:"Abdulsalami Abubakar",optionB:"Obasanjo",optionC:"Babangida",optionD:"Abacha",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What defined the Second Republic?",optionA:"Presidentialism",optionB:"Parliamentary",optionC:"Military",optionD:"Monarchy",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 1986 economic policy?",optionA:"SAP",optionB:"Oil Boom",optionC:"Green Age",optionD:"Industrial Age",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 2007 election dispute?",optionA:"Judicial crisis",optionB:"Tax crisis",optionC:"Land crisis",optionD:"Budget crisis",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 1998 Gani case?",optionA:"Corporate accountability",optionB:"Tax",optionC:"Election",optionD:"Land",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Which city hosted the 1965 refinery?",optionA:"Port Harcourt",optionB:"Lagos",optionC:"Kano",optionD:"Enugu",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"What does the 1914 date signify?",optionA:"Amalgamation",optionB:"Independence",optionC:"Republic",optionD:"War",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"What reached Nigeria in 11th century?",optionA:"Islam",optionB:"Christianity",optionC:"Buddhism",optionD:"Hinduism",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What reached Nigeria in 15th century?",optionA:"Christianity",optionB:"Islam",optionC:"Buddhism",optionD:"Hinduism",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What was the first slave port?",optionA:"Badagry",optionB:"Lagos",optionC:"Kano",optionD:"Enugu",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 1962 census issue?",optionA:"Ethnic tension",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"What led to the 1966 coup?",optionA:"Political collapse",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Who succeeded Ironsi in 1966?",optionA:"Yakubu Gowon",optionB:"Ojukwu",optionC:"Obasanjo",optionD:"Buhari",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What happened in Aburi 1967?",optionA:"Peace talks",optionB:"War",optionC:"Tax",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2004 pension act?",optionA:"Contributory Scheme",optionB:"Old Scheme",optionC:"Grant",optionD:"Loan",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2007 fiscal act?",optionA:"Transparency",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"What ended the 2002 Bakassi crisis?",optionA:"ICJ Ruling",optionB:"War",optionC:"Trade",optionD:"Tax",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2010 bad bank?",optionA:"AMCON",optionB:"CBN",optionC:"Naira",optionD:"Bank",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2007 Amaechi case?",optionA:"Mandate ownership",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2021 oil reform?",optionA:"PIA",optionB:"Oil Act",optionC:"Gas Act",optionD:"Petroleum Act",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What was the 2012 protest name?",optionA:"Occupy Nigeria",optionB:"EndSARS",optionC:"Election",optionD:"Food",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2016 fiscal crisis?",optionA:"Revenue share",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2015 arms case?",optionA:"Corruption",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2014 GDP rebasing?",optionA:"Economic data",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the Sharia debate?",optionA:"Judicial crisis",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2026 debt crisis?",optionA:"Borrowing limit",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What is the 2015 Zaria massacre?",optionA:"Military clash",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"What was the 1978 land law?",optionA:"Land Use Act",optionB:"Property",optionC:"Rent",optionD:"Housing",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2026 census?",optionA:"Population count",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2026 highway project?",optionA:"Coastal Highway",optionB:"Express",optionC:"Rail",optionD:"Air",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 2026 stability focus?",optionA:"Economic reform",optionB:"Tax",optionC:"Land",optionD:"Election",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Who is the first Nigerian leader in 1960?",optionA:"Tafawa Balewa",optionB:"Nnamdi Azikiwe",optionC:"Aguiyi Ironsi",optionD:"Yakubu Gowon",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"What does the green color on flag represent?",optionA:"Agriculture",optionB:"Peace",optionC:"Unity",optionD:"Wealth",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"When did Nigeria adopt the Naira currency?",optionA:"1973",optionB:"1960",optionC:"1999",optionD:"1980",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What is the name of the Senate body?",optionA:"National Assembly",optionB:"Senate House",optionC:"Assembly of Reps",optionD:"Council",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the military leader during the war?",optionA:"Yakubu Gowon",optionB:"Aguiyi Ironsi",optionC:"Olusegun Obasanjo",optionD:"Murtala Mohammed",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What occurred on October 1st 1960?",optionA:"Independence",optionB:"Republic",optionC:"Civil War",optionD:"Amalgamation",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Which city is known as Center of Excellence?",optionA:"Lagos",optionB:"Abuja",optionC:"Kano",optionD:"Enugu",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"What is the largest ethnic group?",optionA:"Hausa-Fulani",optionB:"Yoruba",optionC:"Igbo",optionD:"Ijaw",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"What does BVAS stand for?",optionA:"Voter Accreditation",optionB:"Voter System",optionC:"Voter Count",optionD:"Voter Check",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Which body conducts national elections?",optionA:"INEC",optionB:"EFCC",optionC:"Police",optionD:"Court",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"Where was the first oil discovered?",optionA:"Oloibiri",optionB:"Lagos",optionC:"Kano",optionD:"Enugu",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was president from 2015 to 2023?",optionA:"Muhammadu Buhari",optionB:"Obasanjo",optionC:"Jonathan",optionD:"YarAdua",correctAnswer:"A",category:"nigeria_history",difficulty:"easy"},
{question:"When was the eNaira launched?",optionA:"2021",optionB:"2020",optionC:"2022",optionD:"2023",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"Which year did Nigeria gain formal independence?",optionA:"1960",optionB:"1963",optionC:"1970",optionD:"1999",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"What is Nigeria's official national currency?",optionA:"Naira",optionB:"Dollar",optionC:"Cedi",optionD:"Pound",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Who is the current Nigerian President in 2026?",optionA:"Bola Tinubu",optionB:"Obasanjo",optionC:"Buhari",optionD:"Atiku",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"Which city is the administrative capital?",optionA:"Abuja",optionB:"Lagos",optionC:"Kano",optionD:"Ibadan",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"The 1914 amalgamation joined which two protectorates?",optionA:"North and South",optionB:"East and West",optionC:"Lagos and Kano",optionD:"Borno and Oyo",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Which major religion is prevalent in the North?",optionA:"Islam",optionB:"Christianity",optionC:"Buddhism",optionD:"Hinduism",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"What does the white color represent?",optionA:"Peace",optionB:"Energy",optionC:"Strength",optionD:"Unity",correctAnswer:"B",category:"nigeria_history",difficulty:"easy"},
{question:"When did Nigeria become a republic?",optionA:"1963",optionB:"1960",optionC:"1970",optionD:"1979",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who led the 1966 military coup?",optionA:"Chukwuma Kaduna Nzeogwu",optionB:"Aguiyi Ironsi",optionC:"Yakubu Gowon",optionD:"Murtala Mohammed",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"Which state is known as the Coal City?",optionA:"Enugu",optionB:"Kano",optionC:"Lagos",optionD:"Abuja",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the first female NAFDAC director?",optionA:"Dora Akunyili",optionB:"Grace Alele",optionC:"Funmilayo Kuti",optionD:"Okonjo-Iweala",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Nigeria's national anthem was adopted in what year?",optionA:"1978",optionB:"1960",optionC:"1963",optionD:"1999",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"The Nigerian Civil War ended in what year?",optionA:"1970",optionB:"1967",optionC:"1973",optionD:"1969",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the national football team name?",optionA:"Super Eagles",optionB:"Green Eagles",optionC:"Super Falcons",optionD:"Lions",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which year marked the current democracy?",optionA:"1999",optionB:"1960",optionC:"1963",optionD:"2007",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is the official language of Nigeria?",optionA:"English",optionB:"Hausa",optionC:"Igbo",optionD:"Yoruba",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which industry dominates the Nigerian economy?",optionA:"Petroleum",optionB:"Tourism",optionC:"Fishing",optionD:"Mining",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"What was the 1970s economic period called?",optionA:"Oil Boom",optionB:"Gold Rush",optionC:"Green Age",optionD:"Industrial Age",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Who was the first Nigerian military leader?",optionA:"Aguiyi Ironsi",optionB:"Yakubu Gowon",optionC:"Ibrahim Babangida",optionD:"Muhammadu Buhari",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"What is Nigeria's largest movie industry?",optionA:"Nollywood",optionB:"Hollywood",optionC:"Bollywood",optionD:"Tollywood",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"The 2023 election winner was which candidate?",optionA:"Bola Tinubu",optionB:"Atiku Abubakar",optionC:"Peter Obi",optionD:"Rabiu Kwankwaso",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"Which hero appears on the 20 Naira note?",optionA:"Murtala Mohammed",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Which region sought secession in 1967?",optionA:"Eastern Region",optionB:"Western Region",optionC:"Northern Region",optionD:"Midwest",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Which city was the former capital?",optionA:"Lagos",optionB:"Abuja",optionC:"Kaduna",optionD:"Enugu",correctAnswer:"C",category:"nigeria_history",difficulty:"easy"},
{question:"What is the national motto of Nigeria?",optionA:"Unity and Faith",optionB:"Peace and Love",optionC:"Growth and Power",optionD:"God Bless Nigeria",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which city hosted the 1973 All-Africa Games?",optionA:"Lagos",optionB:"Abuja",optionC:"Kano",optionD:"Enugu",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Which year did the Fourth Republic start?",optionA:"1999",optionB:"1995",optionC:"2000",optionD:"1990",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which court handles regional legal cases?",optionA:"ECOWAS Court",optionB:"Supreme Court",optionC:"High Court",optionD:"Sharia Court",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Who was the first Prime Minister?",optionA:"Tafawa Balewa",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Which colonial leader pushed the amalgamation?",optionA:"Lord Lugard",optionB:"Sir Robertson",optionC:"Mungo Park",optionD:"Flora Shaw",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What does the red color represent?",optionA:"Strength",optionB:"Peace",optionC:"Energy",optionD:"Agriculture",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Which region is historically Northern Nigeria?",optionA:"The North",optionB:"The South",optionC:"The West",optionD:"The East",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Who was the president in 1999?",optionA:"Olusegun Obasanjo",optionB:"Goodluck Jonathan",optionC:"Umaru YarAdua",optionD:"Buhari",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"How many senatorial districts per state?",optionA:"Three",optionB:"Two",optionC:"Four",optionD:"Five",correctAnswer:"D",category:"nigeria_history",difficulty:"easy"},
{question:"Which hero appears on the 50 Naira?",optionA:"Unity Statue",optionB:"Nnamdi Azikiwe",optionC:"Ahmadu Bello",optionD:"Awolowo",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"Which president ended fuel subsidies 2023?",optionA:"Bola Tinubu",optionB:"Buhari",optionC:"Jonathan",optionD:"Obasanjo",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"What is the 1978 land act?",optionA:"Land Use Act",optionB:"Property Act",optionC:"Rent Act",optionD:"Housing Act",correctAnswer:"D",category:"nigeria_history",difficulty:"hard"},
{question:"NIMC Act 2026 replaced which older law?",optionA:"2007 Act",optionB:"2010 Act",optionC:"2005 Act",optionD:"2000 Act",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"NJC recommended new appellate justices in?",optionA:"May-26",optionB:"Jun-26",optionC:"Apr-26",optionD:"Mar-26",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"How many petitions did NJC dismiss?",optionA:"73",optionB:"50",optionC:"100",optionD:"20",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Who was nominated for Supreme Court?",optionA:"Justice Oyewole",optionB:"Justice Ade",optionC:"Justice Dan",optionD:"Justice Ali",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"EFCC and ICPC focus on what?",optionA:"Trial delays",optionB:"Court fees",optionC:"New laws",optionD:"Judges pay",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"State judiciary autonomy is what goal?",optionA:"Constitutional",optionB:"Political",optionC:"Local",optionD:"Global",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Customary courts reinforce what?",optionA:"Grassroots access",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Courts integrate what for crimes?",optionA:"Digital forensics",optionB:"Tax logs",optionC:"Hand notes",optionD:"Oral tales",correctAnswer:"A",category:"nigeria_history",difficulty:"hard"},
{question:"National Assembly and Judiciary align on?",optionA:"Commercial dispute resolution",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Public procurement audits use what?",optionA:"Digital trails",optionB:"Paper files",optionC:"Manual books",optionD:"Oral",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Election petitions undergo what refinement?",optionA:"Process updates",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"Judicial workshops focus on what?",optionA:"Results management",optionB:"Pay",optionC:"Laws",optionD:"Hours",correctAnswer:"A",category:"nigeria_history",difficulty:"medium"},
{question:"NESG 2026 projects what growth?",optionA:"5.50%",optionB:"2%",optionC:"3%",optionD:"1%",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Inflation declined to what in 2025?",optionA:"14.45%",optionB:"20%",optionC:"30%",optionD:"10%",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Ways and Means advances impact what?",optionA:"Fiscal transparency",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Debt-to-GDP ratio stabilized at what?",optionA:"36.10%",optionB:"50%",optionC:"20%",optionD:"10%",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Economic strategy targets what level?",optionA:"Ward-level",optionB:"State-level",optionC:"Global",optionD:"National",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Abubakar Bagudu engaged which investors?",optionA:"German",optionB:"US",optionC:"Chinese",optionD:"Indian",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"New development plan is what?",optionA:"Child-centric",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Local government leads what programs?",optionA:"Social protection",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"MDAs use what management style?",optionA:"Results-based",optionB:"Manual",optionC:"Oral",optionD:"Legacy",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Who verifies state governance performance?",optionA:"Independent agents",optionB:"Gov",optionC:"Local",optionD:"Foreign",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Joseph Tegbe became Minister of?",optionA:"Power",optionB:"Health",optionC:"Works",optionD:"Finance",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"Sola Enikanolaiye became Minister of?",optionA:"Foreign Affairs",optionB:"Health",optionC:"Works",optionD:"Finance",correctAnswer:"B",category:"nigeria_history",difficulty:"hard"},
{question:"NEBM 2026 aligns whom?",optionA:"CEOs and policymakers",optionB:"States",optionC:"Local",optionD:"Global",correctAnswer:"B",category:"nigeria_history",difficulty:"medium"},
{question:"NIMC Act enables tracking of?",optionA:"Terrorism suspects",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Government integrated what databases?",optionA:"Unified",optionB:"State",optionC:"Local",optionD:"Global",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Internal security reform led by?",optionA:"Dr. Tunji-Ojo",optionB:"Dr. Ali",optionC:"Dr. Dan",optionD:"Dr. Ade",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"Digital infrastructure boosts what?",optionA:"Economic trust",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Immigration uses what for security?",optionA:"E-gate tech",optionB:"Paper",optionC:"Manual",optionD:"Oral",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Nigeria-UK project supports what goal?",optionA:"$1 Trillion Economy",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"hard"},
{question:"NEC and State officers reinforce?",optionA:"National security",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Civil service conference held in?",optionA:"May-26",optionB:"Jun-26",optionC:"Apr-26",optionD:"Mar-26",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"NIN data improved what operations?",optionA:"Intelligence-led",optionB:"Manual",optionC:"Paper",optionD:"Oral",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Funding is linked to what?",optionA:"Performance outcomes",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Efforts stabilize what region?",optionA:"Sahel",optionB:"North",optionC:"West",optionD:"East",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"2026 framework provides what?",optionA:"Data protection",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Shared identity data improves?",optionA:"Security synergy",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"C",category:"nigeria_history",difficulty:"medium"},
{question:"Germany-Nigeria focus is?",optionA:"Industrial investment",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Domestic reforms target what?",optionA:"FDI capture",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Key ministers were replaced to?",optionA:"Align priorities",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Policy structured with whom?",optionA:"Global institutions",optionB:"States",optionC:"Local",optionD:"Global",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Sustainability balances growth with?",optionA:"Climate-conscious action",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Governance commits to?",optionA:"Transparency",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"AfCFTA framework promotes?",optionA:"Regional trade",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Ambassadors engage ministries for?",optionA:"Strategic alignment",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Focus shifted to?",optionA:"Growth acceleration",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"CEOs help shape?",optionA:"National outlook",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Capacity building handles?",optionA:"Complex administration",optionB:"Tax",optionC:"Land",optionD:"Trade",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"},
{question:"Long-term plan targets what year?",optionA:"2030",optionB:"2028",optionC:"2035",optionD:"2040",correctAnswer:"D",category:"nigeria_history",difficulty:"medium"}
];
export default nigeriaHistory;